const ACTIVITIES = [
  // ─────────────── Prompt Engineering (PE) ───────────────
  { id:'PE-001', track:'prompt-engineering', title:'The Perfect Prompt', emoji:'💬', difficulty:'beginner', timeEstimate:20,
    description:'Write the same request 5 different ways. Compare outputs. Learn what specificity does.',
    detailedInstructions:'Pick a real work request (e.g. "draft an email to a customer about a delay"). Write it 5 different ways: vague, specific, with role, with constraints, with examples. Run each through the same AI. Capture what changed.',
    tools:['any'], deliverable:'Post your 5 prompts and outputs in the team channel with a 1-line takeaway.',
    skillsBuilt:['prompt-clarity','iteration','specificity'], tags:['warm-up','day-1-friendly'] },
  { id:'PE-002', track:'prompt-engineering', title:'Role Play', emoji:'🎭', difficulty:'beginner', timeEstimate:15,
    description:'Assign AI 5 different expert roles for the same question. See how perspective changes output.',
    detailedInstructions:'Pick one question. Prompt 5 different experts (CFO, lawyer, designer, child, comedian). Compare voice, depth, and recommendations.',
    tools:['any'], deliverable:'Share the funniest and most useful answers from your role-play.',
    skillsBuilt:['role-prompting','perspective-taking'], tags:['warm-up','playful'] },
  { id:'PE-003', track:'prompt-engineering', title:'Chain of Thought', emoji:'🧠', difficulty:'intermediate', timeEstimate:25,
    description:'Force AI to show its reasoning step-by-step. Compare with a one-shot answer.',
    detailedInstructions:'Take a tricky business problem. Solve it twice: once asking for the answer directly, once asking AI to think step-by-step before answering.',
    tools:['any'], deliverable:'Post both answers with a 2-line note on where the reasoning helped.',
    skillsBuilt:['reasoning-prompts','verification'], tags:['analytical'] },
  { id:'PE-004', track:'prompt-engineering', title:'Constraint Boxing', emoji:'📦', difficulty:'intermediate', timeEstimate:20,
    description:'Give AI the same task with increasingly tight constraints (word limit, tone, format).',
    detailedInstructions:'Same task, 4 versions: no constraints, with word limit, with tone, with format. Document how output quality and usability changes.',
    tools:['any'], deliverable:'A side-by-side of the 4 outputs.',
    skillsBuilt:['constraint-design','prompt-shaping'], tags:['practical'] },
  { id:'PE-005', track:'prompt-engineering', title:'Prompt Battle', emoji:'⚔️', difficulty:'intermediate', timeEstimate:30,
    description:'Two people prompt the same AI for the same goal. Compare results. Who got closer?',
    detailedInstructions:'Pair up. Agree on a target outcome. Each writes prompts independently for 15 min. Compare results and vote.',
    tools:['any'], deliverable:'Both prompts, both outputs, a winner and why.',
    skillsBuilt:['critique','peer-learning'], tags:['team','competitive'] },
  { id:'PE-006', track:'prompt-engineering', title:'The Anti-Prompt', emoji:'🙃', difficulty:'advanced', timeEstimate:25,
    description:'Write the worst possible prompt. Then fix it systematically. Document what changed.',
    detailedInstructions:'Compose a maximally bad prompt for a real task. List 5 things wrong with it. Fix them one at a time, re-running each round.',
    tools:['any'], deliverable:'Before/after with a numbered list of fixes.',
    skillsBuilt:['prompt-diagnosis','iteration'], tags:['analytical'] },
  { id:'PE-007', track:'prompt-engineering', title:'Few-Shot Teaching', emoji:'🎓', difficulty:'advanced', timeEstimate:30,
    description:'Teach AI a pattern with 3 examples, then test it on new input.',
    detailedInstructions:'Pick a transformation (e.g. "ticket subject → priority"). Show 3 examples, then test on 5 new inputs.',
    tools:['any'], deliverable:'Your few-shot prompt and the 5 outputs.',
    skillsBuilt:['few-shot','pattern-design'], tags:['technical'] },
  { id:'PE-008', track:'prompt-engineering', title:'System Prompt Architect', emoji:'🏗️', difficulty:'advanced', timeEstimate:35,
    description:'Design a system prompt for a specific use case. Test with 10 different user inputs.',
    detailedInstructions:'Pick a use case (e.g. "internal helpdesk triage"). Write a system prompt with role, constraints, format, examples. Test with 10 diverse user messages.',
    tools:['claude','chatgpt'], deliverable:'System prompt + 10 test transcripts.',
    skillsBuilt:['system-design','testing'], tags:['advanced','design'] },
  { id:'PE-009', track:'prompt-engineering', title:'Prompt Library', emoji:'📚', difficulty:'beginner', timeEstimate:20,
    description:'Build your personal library of 10 reusable prompts for your role.',
    detailedInstructions:'Inventory 10 tasks you do weekly. Write a saveable prompt for each. Save in a doc.',
    tools:['any'], deliverable:'Share your top 3 prompts in the team channel.',
    skillsBuilt:['knowledge-management','reuse'], tags:['practical','keepers'] },
  { id:'PE-010', track:'prompt-engineering', title:'Output Format Forcing', emoji:'📐', difficulty:'intermediate', timeEstimate:20,
    description:'Force AI to produce JSON, markdown table, CSV, and bullet-list versions of the same answer.',
    detailedInstructions:'Pick a research question. Get the answer in 4 formats. Note which AIs respect format best.',
    tools:['any'], deliverable:'Screenshots of all 4 formats.',
    skillsBuilt:['structured-output','format-control'], tags:['technical'] },

  // ─────────────── Content Generation (CG) ───────────────
  { id:'CG-001', track:'content-generation', title:'Tone Tornado', emoji:'🌪️', difficulty:'beginner', timeEstimate:20,
    description:'Rewrite one message in 5 tones: formal, casual, urgent, humorous, executive.',
    detailedInstructions:'Take a real email or update. Rewrite it 5 ways. Pick a favorite and send the polished version.',
    tools:['any'], deliverable:'All 5 versions plus the one you actually sent.',
    skillsBuilt:['tone-control','editorial-judgement'], tags:['practical'] },
  { id:'CG-002', track:'content-generation', title:'Email Transformer', emoji:'✉️', difficulty:'beginner', timeEstimate:15,
    description:'Turn bullet points into a polished email. Then turn a rambling email into bullets.',
    detailedInstructions:'Pick a real rambling email. Distill it. Then take 5 bullets and inflate to a polished email.',
    tools:['any'], deliverable:'Both transformations.',
    skillsBuilt:['expansion','compression'], tags:['day-1-friendly'] },
  { id:'CG-003', track:'content-generation', title:'Content Multiplier', emoji:'🔢', difficulty:'intermediate', timeEstimate:25,
    description:'Take one idea, generate 5 formats: tweet, LinkedIn, email, talking points, one-pager.',
    detailedInstructions:'Pick one insight. Have AI produce 5 distinct formats tailored to channel.',
    tools:['any'], deliverable:'All 5 deliverables in one doc.',
    skillsBuilt:['channel-adaptation','repurposing'], tags:['practical'] },
  { id:'CG-004', track:'content-generation', title:'Meeting Recap Machine', emoji:'📝', difficulty:'intermediate', timeEstimate:20,
    description:'Paste messy notes. Extract summary, action items, and follow-up email.',
    detailedInstructions:'Take real meeting notes. Produce 3 artifacts: TL;DR, action items with owners, draft follow-up email.',
    tools:['any'], deliverable:'All 3 artifacts.',
    skillsBuilt:['summarization','extraction'], tags:['immediate-roi'] },
  { id:'CG-005', track:'content-generation', title:'Ghostwriter Challenge', emoji:'👤', difficulty:'intermediate', timeEstimate:30,
    description:'Give AI samples of your writing. Have it write something new in your voice.',
    detailedInstructions:'Paste 3 samples of your own writing. Ask AI to capture style attributes. Then write a new piece on a fresh topic.',
    tools:['claude','chatgpt'], deliverable:'Your samples summary + the new piece.',
    skillsBuilt:['voice-capture','style-transfer'], tags:['advanced-prompt'] },
  { id:'CG-006', track:'content-generation', title:'Translation Layer', emoji:'🔁', difficulty:'intermediate', timeEstimate:25,
    description:'Take a technical document, translate for 3 audiences: exec, customer, new hire.',
    detailedInstructions:'Pick a technical doc. Produce 3 versions tuned to audience knowledge and goals.',
    tools:['any'], deliverable:'All 3 audience-specific versions.',
    skillsBuilt:['audience-targeting','translation'], tags:['practical'] },
  { id:'CG-007', track:'content-generation', title:'SOW Generator', emoji:'📋', difficulty:'advanced', timeEstimate:40,
    description:'Describe a project verbally. AI produces a full Statement of Work.',
    detailedInstructions:'Voice-record a 5-min project description. Have AI structure into a full SOW: scope, deliverables, timeline, exclusions, pricing model.',
    tools:['any'], deliverable:'The polished SOW.',
    skillsBuilt:['document-generation','structuring'], tags:['high-value'] },
  { id:'CG-008', track:'content-generation', title:'Blog to Deck', emoji:'📰', difficulty:'advanced', timeEstimate:35,
    description:'Turn a blog post into a 10-slide presentation with speaker notes.',
    detailedInstructions:'Take a long blog post. Have AI extract slide structure, headlines, key visuals, and speaker notes.',
    tools:['copilot','chatgpt'], deliverable:'10-slide outline ready to drop into PowerPoint.',
    skillsBuilt:['repurposing','structure'], tags:['advanced'] },
  { id:'CG-009', track:'content-generation', title:'FAQ Forge', emoji:'❓', difficulty:'beginner', timeEstimate:25,
    description:'Generate 15 questions a customer or new hire would ask, with concise answers.',
    detailedInstructions:'Pick a product, policy, or process. Brainstorm questions with AI from 3 personas. Polish top 15.',
    tools:['any'], deliverable:'A 15-question FAQ.',
    skillsBuilt:['anticipation','clarity'], tags:['immediate-roi'] },
  { id:'CG-010', track:'content-generation', title:'Headline Lab', emoji:'🗞️', difficulty:'intermediate', timeEstimate:20,
    description:'Generate 20 headline variants and rank them by clarity, intrigue, and brand fit.',
    detailedInstructions:'Pick a real piece of content. Generate 20 headlines across 4 styles. Rank with AI as critic.',
    tools:['any'], deliverable:'Top 5 with a 1-line rationale per pick.',
    skillsBuilt:['copywriting','iteration'], tags:['marketing'] },

  // ─────────────── Data Analysis (DA) ───────────────
  { id:'DA-001', track:'data-analysis', title:'Make the Data Real', emoji:'🗃️', difficulty:'beginner', timeEstimate:25,
    description:'Generate a realistic synthetic dataset you can safely practice and demo with — no customer data needed.',
    detailedInstructions:'1) Pick a scenario you know well (support tickets, renewals, CSAT responses). 2) List 6–8 columns with realistic value ranges, including messy edge cases: blanks, typos, outliers. 3) Have AI generate 100 rows — demand natural variance, not neat patterns. 4) Audit 10 random rows: would a colleague believe them? Fix anything that feels fake. 5) Save it as your reusable practice dataset for every analysis activity that follows.',
    tools:['claude','chatgpt'], deliverable:'A 100-row CSV a teammate can\'t tell from real data, plus the 3 edge cases you planted deliberately.',
    skillsBuilt:['synthetic-data','data-realism','safe-practice'], tags:['analytics','trainer-asset'] },
  { id:'DA-002', track:'data-analysis', title:'Data Detective', emoji:'🔍', difficulty:'intermediate', timeEstimate:30,
    description:'Have AI hunt for patterns in a dataset — then verify its findings yourself before believing them.',
    detailedInstructions:'1) Load a real dataset (anonymize first — strip names, emails, account IDs) or your DA-001 synthetic set. 2) Tell AI what the data is and ask for a profile: ranges, gaps, oddities. 3) Ask for 5 hypotheses about patterns or anomalies, each with the supporting evidence. 4) Manually verify the 2 most interesting — filter and count the rows yourself; AI miscounts more often than you think. 5) Turn the verified findings into 3 recommended actions with owners.',
    tools:['any'], deliverable:'Top 3 verified findings with their evidence — plus one finding AI got wrong and how you caught it.',
    skillsBuilt:['analysis','verification','insight-generation'], tags:['analytics','verification'] },
  { id:'DA-003', track:'data-analysis', title:'Chart from Chaos', emoji:'📈', difficulty:'intermediate', timeEstimate:25,
    description:'Same data, 3 chart types — learn which form tells the truth and which one misleads.',
    detailedInstructions:'1) Take one dataset with a real question behind it (e.g. where do response times blow up?). 2) Ask AI to recommend 3 chart types and justify each choice. 3) Build all 3. 4) Then ask AI to argue which chart misleads and why — scale tricks, cherry-picked ranges, wrong form for the question. 5) Caption each chart with the single insight a busy exec should take away, 12 words max.',
    tools:['copilot','chatgpt'], deliverable:'3 charts with 12-word insight captions + a note on the one you would NOT show, and why.',
    skillsBuilt:['visualization','chart-choice','captioning'], tags:['analytics'] },
  { id:'DA-004', track:'data-analysis', title:'Formula Wizard', emoji:'🧮', difficulty:'intermediate', timeEstimate:25,
    description:'Describe 3 calculations in plain English. AI writes the formulas — you prove they work.',
    detailedInstructions:'1) Pick 3 real calculations you currently do by hand or avoid (weighted CSAT, SLA compliance %, ticket aging buckets). 2) Describe each in plain English along with your sheet layout. 3) Get the formula plus a plain-English explanation of every part. 4) Test each against 3 rows where you already know the right answer — never trust a formula you haven\'t verified. 5) Install the working versions in your real spreadsheet.',
    tools:['copilot','chatgpt'], deliverable:'3 formulas working in your real spreadsheet, each verified against known-good rows.',
    skillsBuilt:['excel','translation','verification'], tags:['immediate-roi'] },
  { id:'DA-005', track:'data-analysis', title:'Dashboard Builder', emoji:'📊', difficulty:'advanced', timeEstimate:45,
    description:'Build a live dashboard that answers 3 named questions at a glance — validated by a real colleague.',
    detailedInstructions:'1) Write down who the dashboard is for and the 3 questions it must answer at a glance — no chart earns a spot without a question. 2) Feed AI your dataset and the 3 questions. 3) Build an HTML dashboard with 4+ visuals and at least one working filter. 4) Test it on a colleague: can they answer all 3 questions in under 30 seconds each? 5) Iterate on whatever confused them.',
    tools:['claude','lovable'], deliverable:'Working dashboard URL + the 3 questions it answers, validated by a colleague in under 30 seconds each.',
    skillsBuilt:['dashboarding','audience-design','no-code-build'], tags:['build','advanced'] },
  { id:'DA-006', track:'data-analysis', title:'Survey Analyzer', emoji:'📋', difficulty:'advanced', timeEstimate:35,
    description:'Cluster open-text survey answers into themes — with a spot-check so you know the themes are real.',
    detailedInstructions:'1) Take a real survey export (anonymize first — strip names, emails, account IDs). 2) Have AI cluster the open-text answers into themes and count responses per theme. 3) Spot-check: read 10 raw answers yourself and confirm they landed in sensible themes — reassign any that didn\'t. 4) Score sentiment per theme. 5) Draft 5 actions, each tied to a theme, with a suggested owner and a how-we\'d-know-it-worked measure.',
    tools:['any'], deliverable:'Theme table with counts, sentiment per theme, 5 owner-ready actions — plus your 10-answer spot-check verdict.',
    skillsBuilt:['qualitative-analysis','clustering','verification'], tags:['hr','cx'] },
  { id:'DA-007', track:'data-analysis', title:'KPI Storyteller', emoji:'📖', difficulty:'advanced', timeEstimate:30,
    description:'Turn 10 KPIs into the narrative a leader would present — with every number fact-checked.',
    detailedInstructions:'1) Pull 10 real (or DA-001 synthetic) KPIs with current value, prior value, and target. 2) Have AI draft the 3-paragraph narrative a leader would present: context, what changed and why, the ask. 3) Fact-check line by line — every number in the narrative must match your source exactly; AI rounds and invents under narrative pressure. 4) Cut any claim the numbers don\'t support. 5) Read it aloud and tighten it to 90 seconds.',
    tools:['any'], deliverable:'A board-ready narrative, 90 seconds spoken, where every figure traces to your source data.',
    skillsBuilt:['data-storytelling','executive-comms','fact-checking'], tags:['executive'] },
  { id:'DA-008', track:'data-analysis', title:'Cohort Carver', emoji:'👥', difficulty:'intermediate', timeEstimate:30,
    description:'Split customers into cohorts to answer a question that changes a real decision.',
    detailedInstructions:'1) Pick a customer or ticket dataset (anonymized) and a question worth answering — e.g. do high-touch accounts renew better? 2) Have AI propose 3 cohort definitions with exact inclusion logic. 3) Compute the comparison: volumes, averages, rates per cohort. 4) Re-run one cohort\'s numbers yourself to confirm the math holds. 5) Write 2 takeaways and name the one decision this comparison should change.',
    tools:['any'], deliverable:'Cohort definitions, a verified comparison table, and the decision it informs.',
    skillsBuilt:['segmentation','comparison','verification'], tags:['analytics'] },

  // ─────────────── Visual Creation (VC) ───────────────
  { id:'VC-001', track:'visual-creation', title:'Triple Style Portrait', emoji:'🖼️', difficulty:'beginner', timeEstimate:15,
    description:'Generate the same subject in 3 art styles. Compare the outputs.',
    detailedInstructions:'Pick a subject. Generate it in 3 styles (photoreal, watercolor, vector). Compare aesthetics.',
    tools:['copilot','chatgpt','gemini'], deliverable:'3 images with the prompts used.',
    skillsBuilt:['style-prompting','visual-iteration'], tags:['playful'] },
  { id:'VC-002', track:'visual-creation', title:'Alternate Universe', emoji:'🌌', difficulty:'beginner', timeEstimate:20,
    description:'Reimagine a real place in 3 alternate realities.',
    detailedInstructions:'Pick a place. Generate it as cyberpunk, post-apocalyptic, and utopian.',
    tools:['copilot','chatgpt','gemini'], deliverable:'3 images + 1-line caption each.',
    skillsBuilt:['creative-prompting','world-building'], tags:['playful'] },
  { id:'VC-003', track:'visual-creation', title:'Product Concept Art', emoji:'💡', difficulty:'intermediate', timeEstimate:25,
    description:'Invent 3 products. Generate professional concept art for each.',
    detailedInstructions:'Brainstorm 3 product ideas. Generate hero shots, lifestyle context, and packaging mock.',
    tools:['copilot','chatgpt','gemini'], deliverable:'A 3-product concept board.',
    skillsBuilt:['concept-design','prompt-detail'], tags:['design'] },
  { id:'VC-004', track:'visual-creation', title:'From Sketch to Screen', emoji:'✏️', difficulty:'intermediate', timeEstimate:25,
    description:'Hand-draw something. Photo it. AI renders it polished.',
    detailedInstructions:'Hand-sketch a concept. Photograph it. Have AI render a polished, professional version.',
    tools:['chatgpt','gemini'], deliverable:'Sketch + AI render side-by-side.',
    skillsBuilt:['image-to-image','refinement'], tags:['design'] },
  { id:'VC-005', track:'visual-creation', title:'Brand Kit Generator', emoji:'🎨', difficulty:'advanced', timeEstimate:40,
    description:'Describe a brand. AI generates logo concepts, color palette, and style guide.',
    detailedInstructions:'Write a brand brief. Generate 3 logo concepts, palette, typography pairing, and mini style guide.',
    tools:['chatgpt','copilot'], deliverable:'A 1-page brand kit.',
    skillsBuilt:['brand-design','system-thinking'], tags:['design','advanced'] },
  { id:'VC-006', track:'visual-creation', title:'Infographic Builder', emoji:'📐', difficulty:'advanced', timeEstimate:35,
    description:'Turn a data set into a polished infographic using AI.',
    detailedInstructions:'Pick a dataset with 5-7 facts. Generate an infographic layout, then refine.',
    tools:['copilot','chatgpt'], deliverable:'A finished infographic image.',
    skillsBuilt:['visual-data','design-iteration'], tags:['data-viz'] },
  { id:'VC-007', track:'visual-creation', title:'Slide Deck Visuals', emoji:'🖥️', difficulty:'intermediate', timeEstimate:25,
    description:'Generate hero images for a 5-slide deck.',
    detailedInstructions:'Outline 5 slide concepts. Generate one hero image per slide with consistent style.',
    tools:['copilot','gemini'], deliverable:'5 images ready for slides.',
    skillsBuilt:['style-consistency','prompt-iteration'], tags:['marketing'] },

  // ─────────────── Application Building (AB) ───────────────
  { id:'AB-001', track:'application-building', title:'Build a Band', emoji:'🎸', difficulty:'intermediate', timeEstimate:30,
    description:'Build a working musical instrument app in HTML.',
    detailedInstructions:'Use vibe-coding to build a playable HTML instrument (keyboard, drum pad). Share the working file.',
    tools:['claude','lovable','replit'], deliverable:'A working HTML file or hosted URL.',
    skillsBuilt:['no-code-app','interactivity'], tags:['build','playful'] },
  { id:'AB-002', track:'application-building', title:'Standup Bot', emoji:'🤖', difficulty:'intermediate', timeEstimate:30,
    description:'Build a daily standup assistant that formats and copies to clipboard.',
    detailedInstructions:'Build an app with 3 inputs (yesterday/today/blockers), nice formatting, and copy-to-clipboard.',
    tools:['claude','lovable'], deliverable:'Working app URL.',
    skillsBuilt:['build','ux-thinking'], tags:['daily-use'] },
  { id:'AB-003', track:'application-building', title:'Quiz App', emoji:'🧩', difficulty:'intermediate', timeEstimate:30,
    description:'Build an interactive quiz on any topic with scoring.',
    detailedInstructions:'Pick a topic. Have AI generate 10 questions and a scored quiz UI.',
    tools:['claude','lovable','base44'], deliverable:'Working quiz URL.',
    skillsBuilt:['build','content-and-code'], tags:['build'] },
  { id:'AB-004', track:'application-building', title:'Live Dashboard', emoji:'📟', difficulty:'advanced', timeEstimate:45,
    description:'Build a live operational dashboard with animated metrics.',
    detailedInstructions:'Pick a metric set. Build an animated dashboard with 4 KPIs, sparklines, and refresh.',
    tools:['claude','lovable','replit'], deliverable:'Working dashboard URL.',
    skillsBuilt:['data-ui','animation'], tags:['advanced','build'] },
  { id:'AB-005', track:'application-building', title:'Portfolio Page', emoji:'🪪', difficulty:'advanced', timeEstimate:45,
    description:'Build a personal or team portfolio page.',
    detailedInstructions:'Outline content. Build a polished single-page portfolio. Deploy.',
    tools:['claude','lovable','base44'], deliverable:'Live URL of your portfolio.',
    skillsBuilt:['build','design-judgement'], tags:['build'] },
  { id:'AB-006', track:'application-building', title:'Calculator Tool', emoji:'🧰', difficulty:'intermediate', timeEstimate:25,
    description:'Build a specialized calculator for a real work scenario.',
    detailedInstructions:'Pick a calculation you do often (ROI, pricing, capacity). Build a clean UI for it.',
    tools:['claude','lovable'], deliverable:'Working calculator URL.',
    skillsBuilt:['build','utility-design'], tags:['daily-use'] },
  { id:'AB-007', track:'application-building', title:'Booking System', emoji:'📆', difficulty:'advanced', timeEstimate:50,
    description:'Build a room/resource booking interface.',
    detailedInstructions:'Build an interface to book a resource with time slots, capacity, and confirmation.',
    tools:['claude','lovable','base44'], deliverable:'Working booking URL.',
    skillsBuilt:['build','state-management'], tags:['build','advanced'] },
  { id:'AB-008', track:'application-building', title:'Personal Knowledge App', emoji:'🗂️', difficulty:'intermediate', timeEstimate:30,
    description:'Build a searchable notes/snippets app for your role.',
    detailedInstructions:'Build a small CRUD app with search and tags. Seed with 10 entries.',
    tools:['claude','lovable'], deliverable:'Working URL.',
    skillsBuilt:['build','crud-ux'], tags:['build'] },

  // ─────────────── Process Automation (PA) ───────────────
  { id:'PA-001', track:'process-automation', title:'Map It Before You Automate', emoji:'🗺️', difficulty:'intermediate', timeEstimate:35,
    description:'Map a recurring process end-to-end with AI, then score every step for automation potential.',
    detailedInstructions:'1) Pick a process your team runs weekly and describe it to AI step by step — including the ugly parts: rework, waiting, chasing people. 2) Have AI lay it out as a numbered flow with owner, tool, and time per step. 3) Correct it; the first map is always wrong somewhere. 4) Score each step with AI: repetitive? rule-based? high volume? 5) Rank the top 3 automation candidates by time saved vs. effort, and note which one you\'d pilot first.',
    tools:['any'], deliverable:'A corrected process map + top-3 automation candidates, each with a time-saved estimate.',
    skillsBuilt:['process-mapping','automation-scoping','prioritization'], tags:['ops','immediate-roi'] },
  { id:'PA-002', track:'process-automation', title:'Decision Tree', emoji:'🌳', difficulty:'intermediate', timeEstimate:30,
    description:'Turn a decision your team makes inconsistently into an interactive tree — tested against real past cases.',
    detailedInstructions:'1) Pick a decision your team makes inconsistently: escalation, refund approval, priority triage. 2) With AI, make the fuzzy rules explicit — real inputs, real thresholds. 3) Build it as an interactive yes/no tree. 4) Test it against 5 real past cases: does the tree land where your best person would? 5) Fix the branches that disagreed, and list the cases that genuinely need human judgement — those stay human.',
    tools:['claude','lovable'], deliverable:'Working decision-tree URL, validated against 5 past cases, with the human-judgement exceptions listed.',
    skillsBuilt:['decision-modeling','rule-design','validation'], tags:['ops'] },
  { id:'PA-003', track:'process-automation', title:'SOP Generator', emoji:'📑', difficulty:'intermediate', timeEstimate:30,
    description:'Talk through a procedure for 3 minutes. AI structures it — a colleague proves it works.',
    detailedInstructions:'1) Record or type a 3-minute description of a procedure you know cold. 2) Have AI structure it into an SOP: purpose, steps, owner, exceptions, escalation path. 3) Ask AI to interview you — what\'s missing? what goes wrong in practice? — and fold in your answers. 4) The real test: hand it to a colleague who has never done the task, and watch where they stumble. 5) Patch those gaps.',
    tools:['any'], deliverable:'An SOP a colleague followed successfully without asking you a single question.',
    skillsBuilt:['documentation','structuring','user-testing'], tags:['immediate-roi'] },
  { id:'PA-004', track:'process-automation', title:'Onboarding Checklist', emoji:'✅', difficulty:'advanced', timeEstimate:35,
    description:'Build an interactive onboarding checklist — pressure-tested by your newest team member.',
    detailedInstructions:'1) List everything a new team member needs in their first two weeks: accounts, tools, intros, first tasks. 2) Have AI organize it into phases with time estimates and links. 3) Build it as an interactive checklist with progress tracking. 4) Pressure-test it with the newest person on your team: what was missing when THEY joined? 5) Add the 3 things everyone forgets.',
    tools:['claude','lovable','base44'], deliverable:'Working checklist URL, reviewed and amended by your most recent joiner.',
    skillsBuilt:['ux','content-structure','user-testing'], tags:['hr','build'] },
  { id:'PA-005', track:'process-automation', title:'Workflow Optimizer', emoji:'⚙️', difficulty:'advanced', timeEstimate:40,
    description:'Have AI find the bottlenecks in a real workflow — then actually pilot the easiest fix this week.',
    detailedInstructions:'1) Describe a full workflow to AI: who does what, and roughly how long each step takes. 2) Have AI map it and flag bottlenecks, double-handling, and wait states. 3) Ask for 5 improvements ranked by minutes saved per week — force the estimate; vague improvements don\'t count. 4) Sanity-check the math on the top 2. 5) Actually pilot the easiest one this week and record what happened.',
    tools:['any'], deliverable:'Current vs. proposed flow, ranked improvements with minutes-saved estimates, and the result of your one-week pilot.',
    skillsBuilt:['process-analysis','optimization','piloting'], tags:['ops','advanced'] },
  { id:'PA-006', track:'process-automation', title:'Email Triage Rules', emoji:'📧', difficulty:'intermediate', timeEstimate:30,
    description:'Design AI triage rules for a shared inbox — and measure their accuracy against real messages.',
    detailedInstructions:'1) Pull 20 recent messages from a shared inbox (anonymize customer details first). 2) With AI, define 4–6 categories, priority rules, and a template reply per category. 3) Test: have AI classify all 20, then compare against how your team actually handled them. 4) Count the agreement rate and study every miss. 5) Tighten the rules and re-test until you\'d trust them for a first-pass triage.',
    tools:['any'], deliverable:'Triage rulebook + template replies + your measured agreement rate across 20 real messages.',
    skillsBuilt:['categorization','templating','accuracy-testing'], tags:['ops','cx'] },
  { id:'PA-007', track:'process-automation', title:'AI Co-Worker SOP', emoji:'🤝', difficulty:'intermediate', timeEstimate:30,
    description:'Write the SOP for doing a recurring task WITH AI — prompts included, warnings included.',
    detailedInstructions:'1) Pick a task you personally do every week with AI\'s help. 2) Write the SOP for doing it with AI: the exact prompts, what to paste in, and what to check before using the output. 3) Include a what-AI-gets-wrong-here section — that warning is the part only you know. 4) Have a teammate run the task using only your SOP. 5) Refine wherever they got a worse result than you do.',
    tools:['any'], deliverable:'An SOP with embedded prompts that a teammate used to match your output quality.',
    skillsBuilt:['process-design','prompt-embedding','knowledge-transfer'], tags:['ops','daily-use','trainer-asset'] },
  { id:'PA-008', track:'process-automation', title:'Form Auto-Filler', emoji:'📝', difficulty:'intermediate', timeEstimate:25,
    description:'Build a drafter for a form you fill repeatedly — and measure the time it actually saves.',
    detailedInstructions:'1) Pick a form or template you fill repeatedly: case notes, handover docs, status reports. 2) Build a small tool — paste raw context in, get a drafted form out. 3) Use it for real 3 times this week. 4) Time yourself against the manual way, and note the edits you still had to make. 5) Tune the prompt behind it to eliminate your most common edit.',
    tools:['claude','lovable'], deliverable:'Working drafter URL + measured time saved across 3 real uses.',
    skillsBuilt:['automation','templating','measurement'], tags:['ops','build'] },

  // ─────────────── Presentation & Communication (PR) ───────────────
  { id:'PR-001', track:'presentation', title:'Strategy Deck', emoji:'🎯', difficulty:'intermediate', timeEstimate:35,
    description:'Build a 10-slide strategy deck where every slide title states its takeaway.',
    detailedInstructions:'1) Write a 1-page brief on a real initiative: situation, goal, 3 supporting points, the ask. 2) Have AI propose a 10-slide outline — argue with it until the story flows without you narrating the gaps. 3) Make every slide title state its point ("Costs fell 12%", not "Cost Update"). 4) Draft key bullets and speaker notes per slide. 5) Fact-check every number and claim against your brief before you build the deck.',
    tools:['copilot','chatgpt','claude'], deliverable:'A 10-slide deck where each title states its takeaway, fact-checked against your brief.',
    skillsBuilt:['executive-comms','structuring','fact-checking'], tags:['executive'] },
  { id:'PR-002', track:'presentation', title:'Pitch in 60 Seconds', emoji:'⏱️', difficulty:'intermediate', timeEstimate:25,
    description:'Distill a project pitch to 60 seconds — through three record-listen-cut rounds.',
    detailedInstructions:'1) Pick a real project you need buy-in for. 2) Have AI draft a 60-second script: hook, problem, proof, ask. 3) Record yourself delivering it and listen back — you\'ll hear what reads fine but speaks badly. 4) Cut anything you stumbled on; re-record. 5) Three rounds minimum. The final take must land under 60 seconds at a natural pace, not a sprint.',
    tools:['any'], deliverable:'Final script + your recording, timed under 60 seconds at natural pace.',
    skillsBuilt:['compression','clarity','delivery'], tags:['exec'] },
  { id:'PR-003', track:'presentation', title:'Executive Summary', emoji:'🗒️', difficulty:'intermediate', timeEstimate:20,
    description:'Compress a long document to 200 words a leader can act on — with every claim verified.',
    detailedInstructions:'1) Pick a long document that genuinely needs summarizing for a leader. 2) Have AI produce a 200-word summary structured as: TL;DR, what changed, risks, decision needed. 3) Verify every claim against the source — summaries are where AI quietly invents. 4) Ask AI what it left out, and judge whether anything cut was load-bearing. 5) Tighten until a leader could act without opening the original.',
    tools:['any'], deliverable:'A 200-word summary a leader can act on, every claim traceable to the source.',
    skillsBuilt:['compression','executive-judgement','verification'], tags:['exec'] },
  { id:'PR-004', track:'presentation', title:'Video Script', emoji:'🎬', difficulty:'intermediate', timeEstimate:30,
    description:'Script a 2-minute explainer for the topic your audience always gets confused by.',
    detailedInstructions:'1) Pick a topic people repeatedly get confused by — a process, a policy, a product feature. 2) Have AI draft a 2-minute explainer script: scene cues, voiceover, and one concrete example per section. 3) Read it aloud with a timer and cut to fit. 4) Verify every step shown is correct and current — scripts fossilize errors. 5) Storyboard the 5 key visuals, even as rough boxes.',
    tools:['any'], deliverable:'A timed 2-minute script + 5-frame storyboard, technically verified.',
    skillsBuilt:['scriptwriting','visual-thinking','verification'], tags:['marketing','cx'] },
  { id:'PR-005', track:'presentation', title:'Q&A Prep', emoji:'🎤', difficulty:'beginner', timeEstimate:25,
    description:'Generate the 15 questions your audience will ask — including the hostile ones — and rehearse the hardest.',
    detailedInstructions:'1) Paste your deck or talking points. 2) Have AI generate 15 likely questions across three tiers: clarifying, skeptical, hostile. 3) Draft your best answer to each, then have AI attack the weak answers. 4) Rehearse the 5 hardest out loud with AI playing the questioner. 5) Note the one question you still can\'t answer well — that\'s your homework, not your blind spot on the day.',
    tools:['any'], deliverable:'A 15-question Q&A doc tiered by difficulty, with the 5 hardest rehearsed out loud.',
    skillsBuilt:['anticipation','executive-prep','rehearsal'], tags:['exec'] },
  { id:'PR-006', track:'presentation', title:'Stakeholder Map', emoji:'🧑‍🤝‍🧑', difficulty:'intermediate', timeEstimate:25,
    description:'Map stakeholders on influence × interest — and write the plan for the one who could derail you.',
    detailedInstructions:'1) List everyone your project touches: sponsors, blockers, users, the quietly influential. 2) Have AI rate each on influence and interest and place them on the 2×2. 3) Correct it — AI doesn\'t know your politics. 4) For each quadrant, draft the comms approach: what they hear, how often, from whom. 5) Identify the one stakeholder most likely to derail you and write their specific engagement plan.',
    tools:['any'], deliverable:'Stakeholder 2×2 + per-quadrant comms plan + a named derailment-risk engagement plan.',
    skillsBuilt:['stakeholder-mgmt','executive-thinking','planning'], tags:['pm','exec'] },
  { id:'PR-007', track:'presentation', title:'Talking Points Generator', emoji:'🗣️', difficulty:'beginner', timeEstimate:15,
    description:'Five talking points with proof attached, ordered to land — deliverable from memory.',
    detailedInstructions:'1) Pick a real update you owe someone senior this week. 2) Feed AI your raw material and get 5 talking points — each one sentence, each with a number or proof attached. 3) For each point, generate the question a sharp listener would ask, and your one-line answer. 4) Order them so the most important lands first, not last. 5) Test: deliver all 5 from memory.',
    tools:['any'], deliverable:'A 5-point card with anticipated questions — delivered from memory.',
    skillsBuilt:['executive-comms','prep','prioritization'], tags:['exec','immediate-roi'] },
  { id:'PR-008', track:'presentation', title:'Demo Script', emoji:'🎬', difficulty:'intermediate', timeEstimate:30,
    description:'Script a demo with screen cues, timings — and a contingency line for every risky step.',
    detailedInstructions:'1) Outline your demo flow: what you show, in what order, and where the wow moment lands. 2) Have AI write the script with screen cues, timings, and transitions that connect features to the audience\'s pain. 3) Add a contingency line for each risky step — what you say when the thing doesn\'t load. 4) Dry-run it once for real. 5) Cut the section that dragged; every demo has one.',
    tools:['any'], deliverable:'A timed demo script with screen cues and failure contingencies, dry-run once.',
    skillsBuilt:['demo-craft','sequencing','contingency-planning'], tags:['sales','pm'] },
  { id:'PR-009', track:'presentation', title:'Explain It Simply', emoji:'🎨', difficulty:'intermediate', timeEstimate:25,
    description:'Turn the concept you re-explain most often into an explanation that lands the first time.',
    detailedInstructions:'1) Pick the concept you re-explain most often: a policy, a technical limit, a pricing rule. 2) Have AI generate 5 metaphors or analogies — demand ones that respect the listener\'s intelligence. 3) Pick the strongest and build a 3-sentence explanation plus one simple visual around it. 4) Test it on a colleague who doesn\'t know the topic: can they replay it back correctly? 5) Refine whatever they garbled.',
    tools:['any'], deliverable:'A tested 3-sentence explanation + visual that a novice replayed back correctly.',
    skillsBuilt:['simplification','analogy-craft','communication'], tags:['comms','cx'] },

  // ─────────────── Creative & Storytelling (CS) ───────────────
  { id:'CS-001', track:'creative-storytelling', title:'AI Alter Ego', emoji:'🦸', difficulty:'beginner', timeEstimate:15,
    description:'Rewrite your bio as a superhero origin story.',
    detailedInstructions:'Paste your bio. Have AI rewrite as a superhero origin story.',
    tools:['any'], deliverable:'Your origin story.',
    skillsBuilt:['voice','play'], tags:['warm-up','playful'] },
  { id:'CS-002', track:'creative-storytelling', title:'Industry Fable', emoji:'🦊', difficulty:'intermediate', timeEstimate:30,
    description:'Write a short fable set in your industry 5 years from now.',
    detailedInstructions:'Describe your industry. Have AI write a moral fable set 5 years out.',
    tools:['any'], deliverable:'The fable.',
    skillsBuilt:['storytelling','future-thinking'], tags:['playful'] },
  { id:'CS-003', track:'creative-storytelling', title:'Origin Story', emoji:'📖', difficulty:'intermediate', timeEstimate:30,
    description:'Write your professional journey. Illustrate it as a graphic novel.',
    detailedInstructions:'Write your career story. Generate 6 graphic-novel panels with captions.',
    tools:['chatgpt','copilot','gemini'], deliverable:'6-panel sequence.',
    skillsBuilt:['narrative-arc','illustration'], tags:['advanced'] },
  { id:'CS-004', track:'creative-storytelling', title:'AI Original Song', emoji:'🎵', difficulty:'intermediate', timeEstimate:30,
    description:'Write lyrics about your work. Generate the music with AI.',
    detailedInstructions:'Write 16-line lyrics about your team or product. Generate the music.',
    tools:['gemini'], deliverable:'Lyrics + audio file.',
    skillsBuilt:['lyric-writing','music-gen'], tags:['playful'] },
  { id:'CS-005', track:'creative-storytelling', title:'Animated Timeline', emoji:'⏳', difficulty:'intermediate', timeEstimate:30,
    description:'Build an animated timeline of a project or career milestone.',
    detailedInstructions:'List 6-8 milestones. Build an animated HTML timeline.',
    tools:['claude','lovable'], deliverable:'Working timeline URL.',
    skillsBuilt:['narrative-design','animation'], tags:['build'] },

  // ─────────────── Customer Intelligence (CI) ───────────────
  { id:'CI-001', track:'customer-intelligence', title:'Persona Builder', emoji:'👤', difficulty:'intermediate', timeEstimate:30,
    description:'Build 3 personas from real interaction data — every trait evidence-backed, nothing invented.',
    detailedInstructions:'1) Gather raw material from 10 recent customer interactions (anonymize first — strip names, emails, account IDs). 2) Have AI draft 3 personas: goals, frictions, how they measure success, a representative quote. 3) Enforce the evidence rule: every trait must trace to something in your material — delete anything AI invented because it "sounds right". 4) Add a how-we-serve-them-differently section per persona; that\'s what makes it operational. 5) Pressure-test with a teammate: do they recognize these people?',
    tools:['any'], deliverable:'3 evidence-backed personas with a serve-them-differently section, recognized by a teammate.',
    skillsBuilt:['persona-design','evidence-discipline','empathy'], tags:['cx','sales'] },
  { id:'CI-002', track:'customer-intelligence', title:'Sentiment Scanner', emoji:'❤️', difficulty:'intermediate', timeEstimate:30,
    description:'Score sentiment across customer feedback — calibrated against your own hand-labels first.',
    detailedInstructions:'1) Collect 30+ pieces of customer feedback (anonymized). 2) Hand-label 10 of them yourself BEFORE asking AI — that\'s your calibration set. 3) Have AI score sentiment and cluster themes with counts. 4) Compare AI\'s labels to yours: the disagreements are where nuance lives — sarcasm, mixed feelings, the "fine" that isn\'t. Adjust the prompt until agreement is solid. 5) Map each negative theme to one concrete fix worth proposing.',
    tools:['any'], deliverable:'Theme + sentiment table with counts, your 10-item calibration result, and a fix per negative theme.',
    skillsBuilt:['sentiment-analysis','calibration','clustering'], tags:['cx','verification'] },
  { id:'CI-003', track:'customer-intelligence', title:'Journey Mapper', emoji:'🗺️', difficulty:'advanced', timeEstimate:40,
    description:'Map the customer journey grounded in real ticket evidence — ending in one owner-ready fix.',
    detailedInstructions:'1) Define your customer journey stages from first contact to renewal. 2) For each stage, pull real evidence: tickets, comments, drop-off points (anonymized). 3) Have AI map pains and opportunities per stage — grounded in that evidence only, no invented pains. 4) Score each pain by frequency × severity. 5) Take the single worst and write a one-paragraph fix proposal with an owner and a measure of success.',
    tools:['any'], deliverable:'An evidence-grounded journey map + one owner-ready fix proposal for the worst pain point.',
    skillsBuilt:['journey-mapping','evidence-discipline','prioritization'], tags:['cx'] },
  { id:'CI-004', track:'customer-intelligence', title:'Objection Handler', emoji:'🛡️', difficulty:'intermediate', timeEstimate:30,
    description:'Build response frameworks for the 8 pushbacks you actually hear — battle-tested in role-play.',
    detailedInstructions:'1) List the 8 pushbacks you actually hear: pricing, churn threats, competitor comparisons, angry escalations. 2) For each, have AI draft the acknowledgement, the reframe, the evidence to cite, and what NOT to say. 3) Reality-check the evidence — only cite things that are true and current. 4) Role-play the 3 hardest with AI playing an unhappy customer; iterate until your responses feel natural, not scripted. 5) Format as a one-page cheatsheet.',
    tools:['any'], deliverable:'A one-page objection cheatsheet, with the 3 hardest responses battle-tested in role-play.',
    skillsBuilt:['objection-handling','framing','role-play'], tags:['sales','cx'] },
  { id:'CI-005', track:'customer-intelligence', title:'Win/Loss Analyzer', emoji:'🏆', difficulty:'advanced', timeEstimate:35,
    description:'Find real patterns in wins and losses — with case counts, so anecdotes don\'t masquerade as insight.',
    detailedInstructions:'1) Compile notes from 10+ won and lost deals or renewals (anonymized). 2) Have AI extract candidate patterns — with a count of supporting cases for each; a pattern seen once is an anecdote. 3) Ask AI to argue against its own top pattern: what else could explain it? 4) Keep only patterns with 3+ cases and a plausible mechanism. 5) Turn the survivors into 3 recommendations someone could act on next quarter.',
    tools:['any'], deliverable:'Pattern report with case counts, a disconfirming analysis, and 3 actionable recommendations.',
    skillsBuilt:['pattern-recognition','disconfirmation','analysis'], tags:['sales','verification'] },
  { id:'CI-006', track:'customer-intelligence', title:'NPS Narrative', emoji:'💬', difficulty:'intermediate', timeEstimate:25,
    description:'Turn raw NPS comments into a counted, quote-verified narrative leaders will trust.',
    detailedInstructions:'1) Paste a batch of NPS or survey comments (anonymized). 2) Have AI extract the top 3 themes with response counts and 2 verbatim quotes each. 3) Verify every quote exists word-for-word in your source — AI will polish or invent quotes if you let it. 4) Add the movement story: what\'s new versus last period? 5) Close with 3 actions, each linked to a theme and sized: quick win or project.',
    tools:['any'], deliverable:'A 1-page narrative with counted themes, verified verbatim quotes, and sized actions.',
    skillsBuilt:['qualitative-synthesis','quote-verification','cx'], tags:['cx','exec'] },
  { id:'CI-007', track:'customer-intelligence', title:'Churn Autopsy', emoji:'⚰️', difficulty:'advanced', timeEstimate:35,
    description:'Find the real root causes behind churn — and design a prevention play you test on a live account.',
    detailedInstructions:'1) Compile notes on 5+ churned customers (anonymized). 2) Have AI propose root causes per case, pushing past the stated reason to the underlying one — "price" is rarely just price. 3) Cluster causes with counts; separate preventable from not. 4) For the top preventable cause, design a prevention play: the early-warning trigger, who acts, and what they do. 5) Test the trigger against a current at-risk account — would it have fired in time?',
    tools:['any'], deliverable:'A churn pattern report + one prevention play with trigger, owner, and action — tested against a live account.',
    skillsBuilt:['root-cause','prevention-planning','testing'], tags:['cx','strategy'] },
  { id:'CI-008', track:'customer-intelligence', title:'Voice of Customer Digest', emoji:'📣', difficulty:'intermediate', timeEstimate:30,
    description:'Build the reusable prompt that turns a week of tickets into a 10-minute VoC digest.',
    detailedInstructions:'1) Gather one week of support tickets and reviews (anonymized). 2) Build a reusable prompt that outputs your digest: top 3 themes with counts, one notable quote, one number that moved, one emerging signal. 3) Generate this week\'s edition and fact-check it against the raw data. 4) Send it to one stakeholder and ask: what would make you read this every week? 5) Fold their answer into the prompt — the prompt IS the deliverable; next week should take 10 minutes.',
    tools:['any'], deliverable:'This week\'s 1-page digest + the reusable prompt that generates it in 10 minutes.',
    skillsBuilt:['recurring-reporting','prompt-design','synthesis'], tags:['cx','trainer-asset'] },

  // ─────────────── Research & Strategy (RS) ───────────────
  { id:'RS-001', track:'research-strategy', title:'Sparring Session', emoji:'🥊', difficulty:'intermediate', timeEstimate:30,
    description:'Pitch an idea to a merciless AI skeptic for 3 rounds — then put the hardest objection in the one-pager.',
    detailedInstructions:'1) Write your idea as a 5-sentence pitch. 2) Set AI up as a specific skeptic — a CFO guarding budget, an ops lead tired of pilots — and tell it to never agree just to be agreeable. 3) Three rounds: it attacks, you defend, it escalates. 4) Log the objection you couldn\'t answer cleanly — that\'s the pitch\'s real weakness, and it goes in the one-pager, addressed head-on. 5) Write the refined one-pager.',
    tools:['claude','chatgpt'], deliverable:'A one-pager that addresses your hardest objection in print, plus the sparring highlights.',
    skillsBuilt:['critique-resistance','refinement','argumentation'], tags:['strategy'] },
  { id:'RS-002', track:'research-strategy', title:'Competitive Landscape', emoji:'🗺️', difficulty:'intermediate', timeEstimate:35,
    description:'Map your competitive landscape — with hallucinated claims caught and marked before anyone sees them.',
    detailedInstructions:'1) Describe your market and name the players you know. 2) Have AI build a competitor grid: positioning, strengths, target segment, pricing posture. 3) Verification pass — AI states competitor facts with total confidence and invents some of them: check at least 5 specific claims against the companies\' own sites, and mark everything unchecked as ASSUMPTION. 4) Ask where the white space is, then stress-test the answer: why hasn\'t anyone taken it? 5) Write up 3 gaps with a confidence level on each.',
    tools:['any'], deliverable:'A competitor grid with verified vs. assumption claims marked + 3 confidence-rated gap opportunities.',
    skillsBuilt:['competitive-analysis','claim-verification','positioning'], tags:['strategy','verification'] },
  { id:'RS-003', track:'research-strategy', title:'Evidence-Based SWOT', emoji:'🧭', difficulty:'intermediate', timeEstimate:25,
    description:'A SWOT where every bullet carries evidence and ends in a decision — not a wall chart.',
    detailedInstructions:'1) Pick a live initiative — something with a decision actually pending. 2) Have AI draft the SWOT, then enforce the rule: every bullet needs evidence — a number, an event, a quote — or it gets cut. Generic entries like "strong team" die here. 3) Force ranking: which ONE strength do you double down on? which ONE weakness is existential? 4) Convert to 3 decisions with owners — a SWOT that doesn\'t change behavior is decoration. 5) Timebox the whole exercise to 25 minutes.',
    tools:['any'], deliverable:'A SWOT where every bullet has evidence, plus the 3 decisions it produced.',
    skillsBuilt:['strategic-analysis','evidence-discipline','decision-forcing'], tags:['strategy'] },
  { id:'RS-004', track:'research-strategy', title:'Trend Spotter', emoji:'🔭', difficulty:'advanced', timeEstimate:35,
    description:'Surface 5 industry trends, verify each with real sources, and kill the ones that don\'t survive.',
    detailedInstructions:'1) Define your industry and your team\'s slice of it. 2) Have AI propose 5 emerging trends, each with claimed evidence. 3) Verify: find 2 independent real sources per trend — kill any trend you can\'t substantiate; AI citations are sometimes decorative. 4) For the survivors, write the so-what-for-us: one opportunity and one threat each. 5) Rank by how soon they\'ll hit, and flag the one worth a deeper look this quarter.',
    tools:['any'], deliverable:'A trend brief with verified sources and a per-trend so-what — including the trend you killed and why.',
    skillsBuilt:['trend-analysis','source-verification','foresight'], tags:['strategy','exec','verification'] },
  { id:'RS-005', track:'research-strategy', title:'Business Case Builder', emoji:'📈', difficulty:'advanced', timeEstimate:45,
    description:'Build a one-page business case with real numbers, labeled estimates, and a half-benefits stress test.',
    detailedInstructions:'1) Describe a real proposal: the problem, options considered, recommended path. 2) Have AI structure the full case: summary, options with trade-offs, costs and benefits, risks, the ask. 3) Insist on real numbers — pull actual costs and time data; where you must estimate, label it and give a range. 4) Run sensitivity: if benefits land at half, does the case survive? Say so honestly. 5) Compress to one page — if it needs ten, the thinking isn\'t done.',
    tools:['any'], deliverable:'A one-page business case with labeled estimates and a half-benefits sensitivity check.',
    skillsBuilt:['business-modeling','sensitivity-analysis','executive-comms'], tags:['exec','advanced'] },
  { id:'RS-006', track:'research-strategy', title:'Three Futures', emoji:'🔮', difficulty:'advanced', timeEstimate:40,
    description:'Sketch 3 distinct 5-year scenarios with observable signposts — and find your no-regrets moves.',
    detailedInstructions:'1) Describe today honestly: your team, market, constraints. 2) Have AI build 3 genuinely different 5-year scenarios — expansion, disruption, squeeze — each with the story of how it happened. 3) For each, define 2 signposts: things you\'d observe within 18 months that say this future is arriving. 4) The payoff question: what would we do differently TODAY per scenario? Anything you\'d do in all 3 is a no-regrets move — flag those. 5) Keep it to 2 pages.',
    tools:['any'], deliverable:'Three scenarios with 18-month signposts + your no-regrets moves list.',
    skillsBuilt:['scenario-planning','signpost-design','vision'], tags:['strategy','exec'] },
  { id:'RS-007', track:'research-strategy', title:'Hypothesis Tree', emoji:'🌲', difficulty:'intermediate', timeEstimate:35,
    description:'Decompose a strategic question into testable hypotheses — then actually run the cheapest test.',
    detailedInstructions:'1) Pick a strategic question you actually need answered — e.g. why is renewal slipping in segment X? 2) Have AI decompose it into a 3-level hypothesis tree; check that branches don\'t overlap and nothing obvious is missing. 3) For each leaf, define the cheapest test that could kill it. 4) Actually run the cheapest test this week, with AI\'s help on the analysis. 5) Update the tree with what you learned and which branches died.',
    tools:['any'], deliverable:'The tree with a test per leaf + results of the one test you actually ran.',
    skillsBuilt:['decomposition','test-design','strategy'], tags:['strategy','analytics'] },
  { id:'RS-008', track:'research-strategy', title:'Red Team Critique', emoji:'🟥', difficulty:'advanced', timeEstimate:30,
    description:'Let AI attack your plan with 10 ranked strikes — then log each as fix, accept, or rebut.',
    detailedInstructions:'1) Paste your real plan. 2) Set AI up as a red team with a mandate: the 10 most damaging attacks, ranked by severity × likelihood, no politeness. 3) For each attack, decide: FIX (change the plan), ACCEPT (note the risk and why it\'s tolerable), or REBUT (with evidence, not hope). 4) The discipline is writing it down — keep the fix/accept/rebut log. 5) Revise the plan and run one final what-did-I-still-miss pass.',
    tools:['claude','chatgpt'], deliverable:'The revised plan + a 10-attack log marked fix / accept / rebut.',
    skillsBuilt:['stress-testing','risk-triage','strategy'], tags:['strategy','exec'] },

  // ─────────────── Learning & Training Design (LD) ───────────────
  { id:'LD-001', track:'learning-design', title:'Build a Course', emoji:'🏫', difficulty:'advanced', timeEstimate:45,
    description:'Build a fully functional course in SCORM or HTML format.',
    detailedInstructions:'Pick a skill. Outline 5 modules. Have AI build interactive HTML modules with checkpoints.',
    tools:['claude','lovable'], deliverable:'Working course URL.',
    skillsBuilt:['curriculum-design','build'], tags:['l&d','build'] },
  { id:'LD-002', track:'learning-design', title:'Quiz Generator', emoji:'📝', difficulty:'intermediate', timeEstimate:20,
    description:'Give AI a topic. It generates a 10-question quiz with explanations.',
    detailedInstructions:'Pick a topic. Generate 10 multi-format questions with answer keys and explanations.',
    tools:['any'], deliverable:'Final quiz doc.',
    skillsBuilt:['assessment-design','clarity'], tags:['l&d'] },
  { id:'LD-003', track:'learning-design', title:'Knowledge Base', emoji:'📚', difficulty:'advanced', timeEstimate:40,
    description:'Build a searchable FAQ/knowledge base for a team or product.',
    detailedInstructions:'Aggregate 20 questions. Build a searchable KB site.',
    tools:['claude','lovable','base44'], deliverable:'Working KB URL.',
    skillsBuilt:['info-architecture','build'], tags:['l&d','build'] },
  { id:'LD-004', track:'learning-design', title:'Scenario Builder', emoji:'🎬', difficulty:'intermediate', timeEstimate:30,
    description:'Create 5 realistic workplace scenarios for role-play training.',
    detailedInstructions:'Pick a skill. Generate 5 scenarios with characters, context, and ideal response notes.',
    tools:['any'], deliverable:'Scenario pack.',
    skillsBuilt:['scenario-design','training-content'], tags:['l&d'] },
  { id:'LD-005', track:'learning-design', title:'Rubric Designer', emoji:'📏', difficulty:'intermediate', timeEstimate:25,
    description:'Describe an assessment. AI creates a detailed grading rubric.',
    detailedInstructions:'Describe what you assess. Have AI build a 4-level rubric with criteria and descriptors.',
    tools:['any'], deliverable:'The rubric document.',
    skillsBuilt:['rubric-design','assessment'], tags:['l&d'] },

  // ─────────────── Code & Technical (CT) ───────────────
  { id:'CT-001', track:'code-technical', title:'Code Reviewer', emoji:'🧐', difficulty:'intermediate', timeEstimate:25,
    description:'Feed AI a code snippet. Get a review with suggestions.',
    detailedInstructions:'Paste a function. Ask AI for review across correctness, readability, performance, and tests needed.',
    tools:['claude','chatgpt'], deliverable:'Review + applied changes.',
    skillsBuilt:['code-review','critique-use'], tags:['eng'] },
  { id:'CT-002', track:'code-technical', title:'API Doc Generator', emoji:'📘', difficulty:'intermediate', timeEstimate:30,
    description:'Describe an API. AI writes the full documentation.',
    detailedInstructions:'Describe an API. Have AI generate endpoint reference, examples, and error reference.',
    tools:['any'], deliverable:'Markdown API doc.',
    skillsBuilt:['documentation','structuring'], tags:['eng'] },
  { id:'CT-003', track:'code-technical', title:'Test Writer', emoji:'🧪', difficulty:'advanced', timeEstimate:35,
    description:'Give AI a function. It writes unit tests with edge cases.',
    detailedInstructions:'Paste a function. Ask for tests including edge cases and failure modes.',
    tools:['claude','chatgpt'], deliverable:'Test file with passing/failing tests as expected.',
    skillsBuilt:['testing','edge-thinking'], tags:['eng'] },
  { id:'CT-004', track:'code-technical', title:'Regex Builder', emoji:'🔣', difficulty:'intermediate', timeEstimate:20,
    description:'Describe a pattern in English. AI writes and explains the regex.',
    detailedInstructions:'Describe 3 patterns. Get regex, explanation, and 5 test strings.',
    tools:['any'], deliverable:'3 regex with examples.',
    skillsBuilt:['translation','testing'], tags:['eng','immediate-roi'] },
  { id:'CT-005', track:'code-technical', title:'Refactor Together', emoji:'🔧', difficulty:'intermediate', timeEstimate:30,
    description:'Take legacy code. Refactor with AI for clarity and tests.',
    detailedInstructions:'Take a real legacy snippet. Refactor with AI explaining each change.',
    tools:['claude','chatgpt'], deliverable:'Before/after + change log.',
    skillsBuilt:['refactoring','articulation'], tags:['eng'] },
  { id:'CT-006', track:'code-technical', title:'SQL from Plain English', emoji:'🗄️', difficulty:'beginner', timeEstimate:20,
    description:'Describe 3 queries in English. AI writes the SQL and explains.',
    detailedInstructions:'Pick 3 real queries you need. Get SQL + explanation + sample output shape.',
    tools:['any'], deliverable:'3 working SQL queries.',
    skillsBuilt:['sql','translation'], tags:['eng','immediate-roi'] },
  { id:'CT-007', track:'code-technical', title:'Bug Hunter', emoji:'🐛', difficulty:'intermediate', timeEstimate:25,
    description:'Paste a buggy snippet. Walk through the fix with AI as pair.',
    detailedInstructions:'Bring a real bug. Have AI hypothesize causes, suggest tests, then propose a fix.',
    tools:['claude','chatgpt'], deliverable:'Bug + fix + test that catches it.',
    skillsBuilt:['debugging','reasoning'], tags:['eng'] },

  // ─── Extra: Creative & Storytelling ───
  { id:'CS-006', track:'creative-storytelling', title:'Workplace Mythology', emoji:'🗿', difficulty:'intermediate', timeEstimate:25,
    description:'Turn your team\'s rituals into a small mythology with characters and lore.',
    detailedInstructions:'Inventory rituals/quirks. Have AI write a short mythological telling.',
    tools:['any'], deliverable:'2-page mythology.',
    skillsBuilt:['team-storytelling','culture'], tags:['playful','team'] },
  { id:'CS-007', track:'creative-storytelling', title:'Future Headlines', emoji:'📰', difficulty:'beginner', timeEstimate:20,
    description:'Write 5 future-newspaper headlines about your team\'s success in 2030.',
    detailedInstructions:'Brainstorm 5 plausible headlines. Pick a favorite and write the supporting article.',
    tools:['any'], deliverable:'Headlines + 1 article.',
    skillsBuilt:['vision-setting','play'], tags:['warm-up','playful'] },
  { id:'CS-008', track:'creative-storytelling', title:'Mascot Maker', emoji:'🐉', difficulty:'beginner', timeEstimate:20,
    description:'Invent a mascot for your team. Include name, backstory, and visuals.',
    detailedInstructions:'Brainstorm traits. Generate the mascot image and a 100-word backstory.',
    tools:['chatgpt','gemini','copilot'], deliverable:'Image + backstory.',
    skillsBuilt:['brand-building','play'], tags:['playful','team'] },
  { id:'CS-009', track:'creative-storytelling', title:'Day-in-the-Life', emoji:'🌅', difficulty:'intermediate', timeEstimate:25,
    description:'Write a fictional day-in-the-life of your customer 3 years from now.',
    detailedInstructions:'Define your customer 3 years out. Write their full day from wake to sleep.',
    tools:['any'], deliverable:'1-page narrative.',
    skillsBuilt:['empathy','foresight'], tags:['cx','strategy'] },

  // ─── Extra: Learning & Training Design ───
  { id:'LD-006', track:'learning-design', title:'Microlearning Series', emoji:'🧱', difficulty:'intermediate', timeEstimate:30,
    description:'Build a 5-part microlearning series, each <3 minutes.',
    detailedInstructions:'Pick a topic. Outline 5 micro lessons with summary, example, quick check.',
    tools:['any'], deliverable:'5 micro lessons.',
    skillsBuilt:['micro-design','sequencing'], tags:['l&d'] },
  { id:'LD-007', track:'learning-design', title:'Role-Play Sims', emoji:'🎭', difficulty:'intermediate', timeEstimate:30,
    description:'Build 3 role-play simulations for a soft-skill topic.',
    detailedInstructions:'Pick a soft skill. Generate 3 scenarios with branching responses and scoring.',
    tools:['any'], deliverable:'3 scenarios with branches.',
    skillsBuilt:['simulation-design','training-content'], tags:['l&d'] },
  { id:'LD-008', track:'learning-design', title:'Pre/Post Assessment', emoji:'📐', difficulty:'intermediate', timeEstimate:25,
    description:'Design matched pre and post assessments to measure learning gain.',
    detailedInstructions:'Pick a topic. Build a 10-question pre and parallel 10-question post.',
    tools:['any'], deliverable:'Pre + post assessment.',
    skillsBuilt:['assessment-design','measurement'], tags:['l&d'] },

  // ─── Extra: Visual ───
  { id:'VC-008', track:'visual-creation', title:'Icon Set', emoji:'🔣', difficulty:'intermediate', timeEstimate:25,
    description:'Generate a 10-icon set with consistent style for your product.',
    detailedInstructions:'List 10 concepts. Generate icons with a consistent style spec.',
    tools:['chatgpt','copilot'], deliverable:'10 icons in a sheet.',
    skillsBuilt:['style-consistency','icon-design'], tags:['design'] },
  { id:'VC-009', track:'visual-creation', title:'Slide Theme Builder', emoji:'🖼️', difficulty:'intermediate', timeEstimate:25,
    description:'Generate a slide theme: title slide, content slide, divider, closer.',
    detailedInstructions:'Brief your brand vibe. Generate 4 slide templates.',
    tools:['copilot','chatgpt'], deliverable:'4 slide templates.',
    skillsBuilt:['template-design','consistency'], tags:['design'] },

  // ─── Extra: Application Building ───
  { id:'AB-009', track:'application-building', title:'AI Helpdesk Mini', emoji:'🛟', difficulty:'advanced', timeEstimate:45,
    description:'Build a mini helpdesk that classifies and replies to messages.',
    detailedInstructions:'Define categories. Build an interface that classifies an input and drafts a reply.',
    tools:['claude','lovable'], deliverable:'Working helpdesk URL.',
    skillsBuilt:['classification-ui','build'], tags:['build','advanced'] },
  { id:'AB-010', track:'application-building', title:'1-Page Pitch Site', emoji:'📃', difficulty:'intermediate', timeEstimate:30,
    description:'Build a 1-page site pitching an internal idea.',
    detailedInstructions:'Draft your pitch. Build a single-page site with hero, benefits, CTA.',
    tools:['lovable','claude','base44'], deliverable:'Live URL.',
    skillsBuilt:['copy-and-build','marketing-page'], tags:['build'] },

  // ─── Extra: Prompt Engineering ───
  { id:'PE-011', track:'prompt-engineering', title:'Self-Critique Loop', emoji:'🔁', difficulty:'intermediate', timeEstimate:25,
    description:'Have AI critique its own output, then improve. Document the lift.',
    detailedInstructions:'Run a task. Have AI grade itself and rewrite. Compare versions.',
    tools:['any'], deliverable:'Original + critique + revised.',
    skillsBuilt:['self-critique','iteration'], tags:['practical'] },
  { id:'PE-012', track:'prompt-engineering', title:'Prompt Compression', emoji:'🗜️', difficulty:'intermediate', timeEstimate:20,
    description:'Take a long prompt. Compress it without losing fidelity.',
    detailedInstructions:'Pick a long prompt you use. Compress it 50%. Verify the output quality holds.',
    tools:['any'], deliverable:'Long + short + before/after outputs.',
    skillsBuilt:['compression','prompt-economics'], tags:['practical'] },

  // ─── Extra: Content Generation ───
  { id:'CG-011', track:'content-generation', title:'1:1 Prep Pack', emoji:'🪞', difficulty:'beginner', timeEstimate:20,
    description:'Turn quick notes into a polished 1:1 prep doc for a direct.',
    detailedInstructions:'List your raw notes for an upcoming 1:1. Get a structured prep doc back.',
    tools:['any'], deliverable:'A 1:1 prep doc.',
    skillsBuilt:['management','structure'], tags:['mgmt','daily-use'] },
  { id:'CG-012', track:'content-generation', title:'Apology Email', emoji:'🙇', difficulty:'beginner', timeEstimate:15,
    description:'Draft 3 versions of a hard apology email. Pick the most human one.',
    detailedInstructions:'Describe the situation. Get 3 versions across tones. Pick and polish.',
    tools:['any'], deliverable:'The 3 versions + your chosen send.',
    skillsBuilt:['tone','sensitive-comms'], tags:['practical'] }
];

if (typeof module !== 'undefined') module.exports = { ACTIVITIES };
