const ACTIVITIES = [
  // ─────────────── Prompt Engineering (PE) ───────────────
  { id:'PE-001', track:'prompt-engineering', title:'The Perfect Prompt', emoji:'💬', difficulty:'beginner', timeEstimate:20,
    description:'Write the same request 5 different ways. Compare outputs. Learn what specificity does.',
    detailedInstructions:'Pick a real work request (e.g. "draft an email to a customer about a delay"). Write it 5 different ways: vague, specific, with role, with constraints, with examples. Run each through the same AI. Capture what changed.',
    tools:['any'], deliverable:'Post your 5 prompts and outputs in the team channel with a 1-line takeaway.',
    skillsBuilt:['prompt-clarity','iteration','specificity'], tags:['warm-up','day-1-friendly'] },
  { id:'PE-002', track:'prompt-engineering', title:'Role Play', emoji:'🎭', difficulty:'beginner', timeEstimate:15,
    description:'Assign AI 5 different expert roles for the same question. See how perspective changes output.',
    detailedInstructions:'Pick one question. Prompt 5 different experts (CFO, lawyer, designer, child, comedian). Compare voice, depth, and recommendations.',
    tools:['any'], deliverable:'Share the funniest and most useful answers from your role-play.',
    skillsBuilt:['role-prompting','perspective-taking'], tags:['warm-up','playful'] },
  { id:'PE-003', track:'prompt-engineering', title:'Chain of Thought', emoji:'🧠', difficulty:'intermediate', timeEstimate:25,
    description:'Force AI to show its reasoning step-by-step. Compare with a one-shot answer.',
    detailedInstructions:'Take a tricky business problem. Solve it twice: once asking for the answer directly, once asking AI to think step-by-step before answering.',
    tools:['any'], deliverable:'Post both answers with a 2-line note on where the reasoning helped.',
    skillsBuilt:['reasoning-prompts','verification'], tags:['analytical'] },
  { id:'PE-004', track:'prompt-engineering', title:'Constraint Boxing', emoji:'📦', difficulty:'intermediate', timeEstimate:20,
    description:'Give AI the same task with increasingly tight constraints (word limit, tone, format).',
    detailedInstructions:'Same task, 4 versions: no constraints, with word limit, with tone, with format. Document how output quality and usability changes.',
    tools:['any'], deliverable:'A side-by-side of the 4 outputs.',
    skillsBuilt:['constraint-design','prompt-shaping'], tags:['practical'] },
  { id:'PE-005', track:'prompt-engineering', title:'Prompt Battle', emoji:'⚔️', difficulty:'intermediate', timeEstimate:30,
    description:'Two people prompt the same AI for the same goal. Compare results. Who got closer?',
    detailedInstructions:'Pair up. Agree on a target outcome. Each writes prompts independently for 15 min. Compare results and vote.',
    tools:['any'], deliverable:'Both prompts, both outputs, a winner and why.',
    skillsBuilt:['critique','peer-learning'], tags:['team','competitive'] },
  { id:'PE-006', track:'prompt-engineering', title:'The Anti-Prompt', emoji:'🙃', difficulty:'advanced', timeEstimate:25,
    description:'Write the worst possible prompt. Then fix it systematically. Document what changed.',
    detailedInstructions:'Compose a maximally bad prompt for a real task. List 5 things wrong with it. Fix them one at a time, re-running each round.',
    tools:['any'], deliverable:'Before/after with a numbered list of fixes.',
    skillsBuilt:['prompt-diagnosis','iteration'], tags:['analytical'] },
  { id:'PE-007', track:'prompt-engineering', title:'Few-Shot Teaching', emoji:'🎓', difficulty:'advanced', timeEstimate:30,
    description:'Teach AI a pattern with 3 examples, then test it on new input.',
    detailedInstructions:'Pick a transformation (e.g. "ticket subject → priority"). Show 3 examples, then test on 5 new inputs.',
    tools:['any'], deliverable:'Your few-shot prompt and the 5 outputs.',
    skillsBuilt:['few-shot','pattern-design'], tags:['technical'] },
  { id:'PE-008', track:'prompt-engineering', title:'System Prompt Architect', emoji:'🏗️', difficulty:'advanced', timeEstimate:35,
    description:'Design a system prompt for a specific use case. Test with 10 different user inputs.',
    detailedInstructions:'Pick a use case (e.g. "internal helpdesk triage"). Write a system prompt with role, constraints, format, examples. Test with 10 diverse user messages.',
    tools:['claude','chatgpt'], deliverable:'System prompt + 10 test transcripts.',
    skillsBuilt:['system-design','testing'], tags:['advanced','design'] },
  { id:'PE-009', track:'prompt-engineering', title:'Prompt Library', emoji:'📚', difficulty:'beginner', timeEstimate:20,
    description:'Build your personal library of 10 reusable prompts for your role.',
    detailedInstructions:'Inventory 10 tasks you do weekly. Write a saveable prompt for each. Save in a doc.',
    tools:['any'], deliverable:'Share your top 3 prompts in the team channel.',
    skillsBuilt:['knowledge-management','reuse'], tags:['practical','keepers'] },
  { id:'PE-010', track:'prompt-engineering', title:'Output Format Forcing', emoji:'📐', difficulty:'intermediate', timeEstimate:20,
    description:'Force AI to produce JSON, markdown table, CSV, and bullet-list versions of the same answer.',
    detailedInstructions:'Pick a research question. Get the answer in 4 formats. Note which AIs respect format best.',
    tools:['any'], deliverable:'Screenshots of all 4 formats.',
    skillsBuilt:['structured-output','format-control'], tags:['technical'] },

  // ─────────────── Content Generation (CG) ───────────────
  { id:'CG-001', track:'content-generation', title:'Tone Tornado', emoji:'🌪️', difficulty:'beginner', timeEstimate:20,
    description:'Rewrite one message in 5 tones: formal, casual, urgent, humorous, executive.',
    detailedInstructions:'Take a real email or update. Rewrite it 5 ways. Pick a favorite and send the polished version.',
    tools:['any'], deliverable:'All 5 versions plus the one you actually sent.',
    skillsBuilt:['tone-control','editorial-judgement'], tags:['practical'] },
  { id:'CG-002', track:'content-generation', title:'Email Transformer', emoji:'✉️', difficulty:'beginner', timeEstimate:15,
    description:'Turn bullet points into a polished email. Then turn a rambling email into bullets.',
    detailedInstructions:'Pick a real rambling email. Distill it. Then take 5 bullets and inflate to a polished email.',
    tools:['any'], deliverable:'Both transformations.',
    skillsBuilt:['expansion','compression'], tags:['day-1-friendly'] },
  { id:'CG-003', track:'content-generation', title:'Content Multiplier', emoji:'🔢', difficulty:'intermediate', timeEstimate:25,
    description:'Take one idea, generate 5 formats: tweet, LinkedIn, email, talking points, one-pager.',
    detailedInstructions:'Pick one insight. Have AI produce 5 distinct formats tailored to channel.',
    tools:['any'], deliverable:'All 5 deliverables in one doc.',
    skillsBuilt:['channel-adaptation','repurposing'], tags:['practical'] },
  { id:'CG-004', track:'content-generation', title:'Meeting Recap Machine', emoji:'📝', difficulty:'intermediate', timeEstimate:20,
    description:'Paste messy notes. Extract summary, action items, and follow-up email.',
    detailedInstructions:'Take real meeting notes. Produce 3 artifacts: TL;DR, action items with owners, draft follow-up email.',
    tools:['any'], deliverable:'All 3 artifacts.',
    skillsBuilt:['summarization','extraction'], tags:['immediate-roi'] },
  { id:'CG-005', track:'content-generation', title:'Ghostwriter Challenge', emoji:'👤', difficulty:'intermediate', timeEstimate:30,
    description:'Give AI samples of your writing. Have it write something new in your voice.',
    detailedInstructions:'Paste 3 samples of your own writing. Ask AI to capture style attributes. Then write a new piece on a fresh topic.',
    tools:['claude','chatgpt'], deliverable:'Your samples summary + the new piece.',
    skillsBuilt:['voice-capture','style-transfer'], tags:['advanced-prompt'] },
  { id:'CG-006', track:'content-generation', title:'Translation Layer', emoji:'🔁', difficulty:'intermediate', timeEstimate:25,
    description:'Take a technical document, translate for 3 audiences: exec, customer, new hire.',
    detailedInstructions:'Pick a technical doc. Produce 3 versions tuned to audience knowledge and goals.',
    tools:['any'], deliverable:'All 3 audience-specific versions.',
    skillsBuilt:['audience-targeting','translation'], tags:['practical'] },
  { id:'CG-007', track:'content-generation', title:'SOW Generator', emoji:'📋', difficulty:'advanced', timeEstimate:40,
    description:'Describe a project verbally. AI produces a full Statement of Work.',
    detailedInstructions:'Voice-record a 5-min project description. Have AI structure into a full SOW: scope, deliverables, timeline, exclusions, pricing model.',
    tools:['any'], deliverable:'The polished SOW.',
    skillsBuilt:['document-generation','structuring'], tags:['high-value'] },
  { id:'CG-008', track:'content-generation', title:'Blog to Deck', emoji:'📰', difficulty:'advanced', timeEstimate:35,
    description:'Turn a blog post into a 10-slide presentation with speaker notes.',
    detailedInstructions:'Take a long blog post. Have AI extract slide structure, headlines, key visuals, and speaker notes.',
    tools:['copilot','chatgpt'], deliverable:'10-slide outline ready to drop into PowerPoint.',
    skillsBuilt:['repurposing','structure'], tags:['advanced'] },
  { id:'CG-009', track:'content-generation', title:'FAQ Forge', emoji:'❓', difficulty:'beginner', timeEstimate:25,
    description:'Generate 15 questions a customer or new hire would ask, with concise answers.',
    detailedInstructions:'Pick a product, policy, or process. Brainstorm questions with AI from 3 personas. Polish top 15.',
    tools:['any'], deliverable:'A 15-question FAQ.',
    skillsBuilt:['anticipation','clarity'], tags:['immediate-roi'] },
  { id:'CG-010', track:'content-generation', title:'Headline Lab', emoji:'🗞️', difficulty:'intermediate', timeEstimate:20,
    description:'Generate 20 headline variants and rank them by clarity, intrigue, and brand fit.',
    detailedInstructions:'Pick a real piece of content. Generate 20 headlines across 4 styles. Rank with AI as critic.',
    tools:['any'], deliverable:'Top 5 with a 1-line rationale per pick.',
    skillsBuilt:['copywriting','iteration'], tags:['marketing'] },

  // ─────────────── Data Analysis (DA) ───────────────
  { id:'DA-001', track:'data-analysis', title:'Make the Data Real', emoji:'🗃️', difficulty:'beginner', timeEstimate:25,
    description:'Generate a realistic synthetic dataset for a business scenario.',
    detailedInstructions:'Pick a scenario (sales pipeline, support tickets, headcount). Have AI generate 100 rows with realistic values and natural variance.',
    tools:['claude','chatgpt'], deliverable:'CSV/table of 100 rows + 3 observations.',
    skillsBuilt:['synthetic-data','scenario-design'], tags:['analytics'] },
  { id:'DA-002', track:'data-analysis', title:'Data Detective', emoji:'🔍', difficulty:'intermediate', timeEstimate:30,
    description:'Feed AI real data. Ask it to find patterns, anomalies, and recommendations.',
    detailedInstructions:'Use a (non-sensitive) dataset. Ask AI for patterns, outliers, and 3 actions you could take.',
    tools:['any'], deliverable:'Top 3 findings with the data that supports them.',
    skillsBuilt:['analysis','insight-generation'], tags:['analytics'] },
  { id:'DA-003', track:'data-analysis', title:'Chart from Chaos', emoji:'📈', difficulty:'intermediate', timeEstimate:25,
    description:'Raw data → 3 different chart types. One-line insight per chart.',
    detailedInstructions:'Use the same dataset. Ask AI to recommend and produce 3 charts. Caption each with the insight.',
    tools:['copilot','chatgpt'], deliverable:'3 chart images + 3 captions.',
    skillsBuilt:['visualization','captioning'], tags:['analytics'] },
  { id:'DA-004', track:'data-analysis', title:'Formula Wizard', emoji:'🧮', difficulty:'intermediate', timeEstimate:25,
    description:'Describe 3 calculations in English. AI writes the Excel formulas and explains them.',
    detailedInstructions:'Pick 3 real calculations you struggle with. Get formulas, an explanation, and a test case.',
    tools:['copilot','chatgpt'], deliverable:'The 3 formulas, working in your spreadsheet.',
    skillsBuilt:['excel','translation'], tags:['immediate-roi'] },
  { id:'DA-005', track:'data-analysis', title:'Dashboard Builder', emoji:'📊', difficulty:'advanced', timeEstimate:45,
    description:'Build a live interactive dashboard with 4+ chart types using AI.',
    detailedInstructions:'Pick a dataset. Have AI build an HTML+Chart.js dashboard with 4 visualizations and filters.',
    tools:['claude','lovable'], deliverable:'A working dashboard URL or screen recording.',
    skillsBuilt:['dashboarding','no-code-build'], tags:['build','advanced'] },
  { id:'DA-006', track:'data-analysis', title:'Survey Analyzer', emoji:'📋', difficulty:'advanced', timeEstimate:35,
    description:'Feed survey results to AI. Get themes, sentiment, and action items.',
    detailedInstructions:'Use real (anonymized) survey data. Have AI cluster open-text answers, score sentiment, and propose 5 actions.',
    tools:['any'], deliverable:'Themes, sentiment chart, action list.',
    skillsBuilt:['qualitative-analysis','clustering'], tags:['hr','cx'] },
  { id:'DA-007', track:'data-analysis', title:'KPI Storyteller', emoji:'📖', difficulty:'advanced', timeEstimate:30,
    description:'Give AI 10 KPIs. Have it write the narrative a CFO would present to the board.',
    detailedInstructions:'Pull 10 real (or synthetic) KPIs. Have AI craft a 3-paragraph board-ready narrative with context, trend, and ask.',
    tools:['any'], deliverable:'The board narrative.',
    skillsBuilt:['data-storytelling','executive-comms'], tags:['executive'] },
  { id:'DA-008', track:'data-analysis', title:'Cohort Carver', emoji:'👥', difficulty:'intermediate', timeEstimate:30,
    description:'Define 3 customer cohorts from your data and compare their behavior.',
    detailedInstructions:'Pick a customer-data scenario. Ask AI to define cohort logic, compute comparisons, and explain differences.',
    tools:['any'], deliverable:'Cohort definitions + comparison table + 2 takeaways.',
    skillsBuilt:['segmentation','comparison'], tags:['analytics'] },

  // ─────────────── Visual Creation (VC) ───────────────
  { id:'VC-001', track:'visual-creation', title:'Triple Style Portrait', emoji:'🖼️', difficulty:'beginner', timeEstimate:15,
    description:'Generate the same subject in 3 art styles. Compare the outputs.',
    detailedInstructions:'Pick a subject. Generate it in 3 styles (photoreal, watercolor, vector). Compare aesthetics.',
    tools:['copilot','chatgpt','gemini'], deliverable:'3 images with the prompts used.',
    skillsBuilt:['style-prompting','visual-iteration'], tags:['playful'] },
  { id:'VC-002', track:'visual-creation', title:'Alternate Universe', emoji:'🌌', difficulty:'beginner', timeEstimate:20,
    description:'Reimagine a real place in 3 alternate realities.',
    detailedInstructions:'Pick a place. Generate it as cyberpunk, post-apocalyptic, and utopian.',
    tools:['copilot','chatgpt','gemini'], deliverable:'3 images + 1-line caption each.',
    skillsBuilt:['creative-prompting','world-building'], tags:['playful'] },
  { id:'VC-003', track:'visual-creation', title:'Product Concept Art', emoji:'💡', difficulty:'intermediate', timeEstimate:25,
    description:'Invent 3 products. Generate professional concept art for each.',
    detailedInstructions:'Brainstorm 3 product ideas. Generate hero shots, lifestyle context, and packaging mock.',
    tools:['copilot','chatgpt','gemini'], deliverable:'A 3-product concept board.',
    skillsBuilt:['concept-design','prompt-detail'], tags:['design'] },
  { id:'VC-004', track:'visual-creation', title:'From Sketch to Screen', emoji:'✏️', difficulty:'intermediate', timeEstimate:25,
    description:'Hand-draw something. Photo it. AI renders it polished.',
    detailedInstructions:'Hand-sketch a concept. Photograph it. Have AI render a polished, professional version.',
    tools:['chatgpt','gemini'], deliverable:'Sketch + AI render side-by-side.',
    skillsBuilt:['image-to-image','refinement'], tags:['design'] },
  { id:'VC-005', track:'visual-creation', title:'Brand Kit Generator', emoji:'🎨', difficulty:'advanced', timeEstimate:40,
    description:'Describe a brand. AI generates logo concepts, color palette, and style guide.',
    detailedInstructions:'Write a brand brief. Generate 3 logo concepts, palette, typography pairing, and mini style guide.',
    tools:['chatgpt','copilot'], deliverable:'A 1-page brand kit.',
    skillsBuilt:['brand-design','system-thinking'], tags:['design','advanced'] },
  { id:'VC-006', track:'visual-creation', title:'Infographic Builder', emoji:'📐', difficulty:'advanced', timeEstimate:35,
    description:'Turn a data set into a polished infographic using AI.',
    detailedInstructions:'Pick a dataset with 5-7 facts. Generate an infographic layout, then refine.',
    tools:['copilot','chatgpt'], deliverable:'A finished infographic image.',
    skillsBuilt:['visual-data','design-iteration'], tags:['data-viz'] },
  { id:'VC-007', track:'visual-creation', title:'Slide Deck Visuals', emoji:'🖥️', difficulty:'intermediate', timeEstimate:25,
    description:'Generate hero images for a 5-slide deck.',
    detailedInstructions:'Outline 5 slide concepts. Generate one hero image per slide with consistent style.',
    tools:['copilot','gemini'], deliverable:'5 images ready for slides.',
    skillsBuilt:['style-consistency','prompt-iteration'], tags:['marketing'] },

  // ─────────────── Application Building (AB) ───────────────
  { id:'AB-001', track:'application-building', title:'Build a Band', emoji:'🎸', difficulty:'intermediate', timeEstimate:30,
    description:'Build a working musical instrument app in HTML.',
    detailedInstructions:'Use vibe-coding to build a playable HTML instrument (keyboard, drum pad). Share the working file.',
    tools:['claude','lovable','replit'], deliverable:'A working HTML file or hosted URL.',
    skillsBuilt:['no-code-app','interactivity'], tags:['build','playful'] },
  { id:'AB-002', track:'application-building', title:'Standup Bot', emoji:'🤖', difficulty:'intermediate', timeEstimate:30,
    description:'Build a daily standup assistant that formats and copies to clipboard.',
    detailedInstructions:'Build an app with 3 inputs (yesterday/today/blockers), nice formatting, and copy-to-clipboard.',
    tools:['claude','lovable'], deliverable:'Working app URL.',
    skillsBuilt:['build','ux-thinking'], tags:['daily-use'] },
  { id:'AB-003', track:'application-building', title:'Quiz App', emoji:'🧩', difficulty:'intermediate', timeEstimate:30,
    description:'Build an interactive quiz on any topic with scoring.',
    detailedInstructions:'Pick a topic. Have AI generate 10 questions and a scored quiz UI.',
    tools:['claude','lovable','base44'], deliverable:'Working quiz URL.',
    skillsBuilt:['build','content-and-code'], tags:['build'] },
  { id:'AB-004', track:'application-building', title:'Live Dashboard', emoji:'📟', difficulty:'advanced', timeEstimate:45,
    description:'Build a live operational dashboard with animated metrics.',
    detailedInstructions:'Pick a metric set. Build an animated dashboard with 4 KPIs, sparklines, and refresh.',
    tools:['claude','lovable','replit'], deliverable:'Working dashboard URL.',
    skillsBuilt:['data-ui','animation'], tags:['advanced','build'] },
  { id:'AB-005', track:'application-building', title:'Portfolio Page', emoji:'🪪', difficulty:'advanced', timeEstimate:45,
    description:'Build a personal or team portfolio page.',
    detailedInstructions:'Outline content. Build a polished single-page portfolio. Deploy.',
    tools:['claude','lovable','base44'], deliverable:'Live URL of your portfolio.',
    skillsBuilt:['build','design-judgement'], tags:['build'] },
  { id:'AB-006', track:'application-building', title:'Calculator Tool', emoji:'🧰', difficulty:'intermediate', timeEstimate:25,
    description:'Build a specialized calculator for a real work scenario.',
    detailedInstructions:'Pick a calculation you do often (ROI, pricing, capacity). Build a clean UI for it.',
    tools:['claude','lovable'], deliverable:'Working calculator URL.',
    skillsBuilt:['build','utility-design'], tags:['daily-use'] },
  { id:'AB-007', track:'application-building', title:'Booking System', emoji:'📆', difficulty:'advanced', timeEstimate:50,
    description:'Build a room/resource booking interface.',
    detailedInstructions:'Build an interface to book a resource with time slots, capacity, and confirmation.',
    tools:['claude','lovable','base44'], deliverable:'Working booking URL.',
    skillsBuilt:['build','state-management'], tags:['build','advanced'] },
  { id:'AB-008', track:'application-building', title:'Personal Knowledge App', emoji:'🗂️', difficulty:'intermediate', timeEstimate:30,
    description:'Build a searchable notes/snippets app for your role.',
    detailedInstructions:'Build a small CRUD app with search and tags. Seed with 10 entries.',
    tools:['claude','lovable'], deliverable:'Working URL.',
    skillsBuilt:['build','crud-ux'], tags:['build'] },

  // ─────────────── Process Automation (PA) ───────────────
  { id:'PA-001', track:'process-automation', title:'Process Flow Animation', emoji:'🌀', difficulty:'intermediate', timeEstimate:30,
    description:'Describe a 5-step process. AI builds an animated flowchart.',
    detailedInstructions:'Describe a real process. Have AI generate an animated SVG/HTML flowchart.',
    tools:['claude','lovable'], deliverable:'Animated flowchart URL or video.',
    skillsBuilt:['process-mapping','visualization'], tags:['ops'] },
  { id:'PA-002', track:'process-automation', title:'Decision Tree', emoji:'🌳', difficulty:'intermediate', timeEstimate:25,
    description:'Map a real decision process as an interactive decision tree.',
    detailedInstructions:'Pick a recurring decision (escalation path, vendor choice). Build an interactive tree.',
    tools:['claude','lovable'], deliverable:'Working tree URL.',
    skillsBuilt:['decision-modeling','ux'], tags:['ops'] },
  { id:'PA-003', track:'process-automation', title:'SOP Generator', emoji:'📑', difficulty:'intermediate', timeEstimate:30,
    description:'Describe a procedure verbally. AI produces a formatted SOP.',
    detailedInstructions:'Record a 3-min description of a procedure. Have AI extract and format into a polished SOP.',
    tools:['any'], deliverable:'The finished SOP.',
    skillsBuilt:['documentation','structuring'], tags:['immediate-roi'] },
  { id:'PA-004', track:'process-automation', title:'Onboarding Checklist', emoji:'✅', difficulty:'advanced', timeEstimate:35,
    description:'Build an interactive onboarding checklist app for new hires.',
    detailedInstructions:'List your onboarding steps. Build an interactive checklist with progress and links.',
    tools:['claude','lovable','base44'], deliverable:'Working checklist URL.',
    skillsBuilt:['ux','content-structure'], tags:['hr','build'] },
  { id:'PA-005', track:'process-automation', title:'Workflow Optimizer', emoji:'⚙️', difficulty:'advanced', timeEstimate:40,
    description:'Describe a current workflow. AI identifies bottlenecks and proposes improvements.',
    detailedInstructions:'Describe a workflow in detail. Ask AI to map it, score each step, and propose 5 improvements with rationale.',
    tools:['any'], deliverable:'Current vs. proposed flow + improvement list.',
    skillsBuilt:['process-analysis','optimization'], tags:['ops','advanced'] },
  { id:'PA-006', track:'process-automation', title:'Email Triage Rules', emoji:'📧', difficulty:'intermediate', timeEstimate:25,
    description:'Design AI-assisted triage rules for a shared inbox.',
    detailedInstructions:'Pick a real inbox. With AI, design categorization, priority rules, and template replies.',
    tools:['any'], deliverable:'Rules doc + 3 example replies.',
    skillsBuilt:['categorization','templating'], tags:['ops'] },

  // ─────────────── Presentation & Communication (PR) ───────────────
  { id:'PR-001', track:'presentation', title:'Strategy Deck', emoji:'🎯', difficulty:'intermediate', timeEstimate:35,
    description:'Build a 10-slide strategy deck from a 1-page brief.',
    detailedInstructions:'Write a 1-page brief on a real initiative. Have AI structure 10 slides with titles, key points, and speaker notes.',
    tools:['copilot','chatgpt','claude'], deliverable:'Final 10-slide deck.',
    skillsBuilt:['executive-comms','structuring'], tags:['executive'] },
  { id:'PR-002', track:'presentation', title:'Pitch in 60 Seconds', emoji:'⏱️', difficulty:'intermediate', timeEstimate:25,
    description:'Distill a project pitch into a 60-second script.',
    detailedInstructions:'Pick a real project. Get AI to draft a 60-sec script. Time it. Iterate 3 times.',
    tools:['any'], deliverable:'Final script + recording.',
    skillsBuilt:['compression','clarity'], tags:['exec'] },
  { id:'PR-003', track:'presentation', title:'Executive Summary', emoji:'🗒️', difficulty:'intermediate', timeEstimate:20,
    description:'Turn a long document into a 200-word executive summary.',
    detailedInstructions:'Pick a long doc. Generate exec summary with TL;DR, key risks, and decision-needed.',
    tools:['any'], deliverable:'The 200-word summary.',
    skillsBuilt:['compression','executive-judgement'], tags:['exec'] },
  { id:'PR-004', track:'presentation', title:'Video Script', emoji:'🎬', difficulty:'intermediate', timeEstimate:30,
    description:'Write a 2-min explainer script with scene directions.',
    detailedInstructions:'Pick a topic. Generate a script with scene/visual cues, voiceover, and pacing.',
    tools:['any'], deliverable:'The script.',
    skillsBuilt:['scriptwriting','visual-thinking'], tags:['marketing'] },
  { id:'PR-005', track:'presentation', title:'Q&A Prep', emoji:'🎤', difficulty:'beginner', timeEstimate:20,
    description:'Generate 15 likely questions and prepared answers for a presentation.',
    detailedInstructions:'Paste your deck/notes. Have AI generate audience questions and your best answers.',
    tools:['any'], deliverable:'Q&A doc with 15 entries.',
    skillsBuilt:['anticipation','executive-prep'], tags:['exec'] },

  // ─────────────── Creative & Storytelling (CS) ───────────────
  { id:'CS-001', track:'creative-storytelling', title:'AI Alter Ego', emoji:'🦸', difficulty:'beginner', timeEstimate:15,
    description:'Rewrite your bio as a superhero origin story.',
    detailedInstructions:'Paste your bio. Have AI rewrite as a superhero origin story.',
    tools:['any'], deliverable:'Your origin story.',
    skillsBuilt:['voice','play'], tags:['warm-up','playful'] },
  { id:'CS-002', track:'creative-storytelling', title:'Industry Fable', emoji:'🦊', difficulty:'intermediate', timeEstimate:30,
    description:'Write a short fable set in your industry 5 years from now.',
    detailedInstructions:'Describe your industry. Have AI write a moral fable set 5 years out.',
    tools:['any'], deliverable:'The fable.',
    skillsBuilt:['storytelling','future-thinking'], tags:['playful'] },
  { id:'CS-003', track:'creative-storytelling', title:'Origin Story', emoji:'📖', difficulty:'intermediate', timeEstimate:30,
    description:'Write your professional journey. Illustrate it as a graphic novel.',
    detailedInstructions:'Write your career story. Generate 6 graphic-novel panels with captions.',
    tools:['chatgpt','copilot','gemini'], deliverable:'6-panel sequence.',
    skillsBuilt:['narrative-arc','illustration'], tags:['advanced'] },
  { id:'CS-004', track:'creative-storytelling', title:'AI Original Song', emoji:'🎵', difficulty:'intermediate', timeEstimate:30,
    description:'Write lyrics about your work. Generate the music with AI.',
    detailedInstructions:'Write 16-line lyrics about your team or product. Generate the music.',
    tools:['gemini'], deliverable:'Lyrics + audio file.',
    skillsBuilt:['lyric-writing','music-gen'], tags:['playful'] },
  { id:'CS-005', track:'creative-storytelling', title:'Animated Timeline', emoji:'⏳', difficulty:'intermediate', timeEstimate:30,
    description:'Build an animated timeline of a project or career milestone.',
    detailedInstructions:'List 6-8 milestones. Build an animated HTML timeline.',
    tools:['claude','lovable'], deliverable:'Working timeline URL.',
    skillsBuilt:['narrative-design','animation'], tags:['build'] },

  // ─────────────── Customer Intelligence (CI) ───────────────
  { id:'CI-001', track:'customer-intelligence', title:'Persona Builder', emoji:'👤', difficulty:'intermediate', timeEstimate:25,
    description:'Describe your customer base. AI builds 3 detailed buyer personas.',
    detailedInstructions:'Describe your real customers. Have AI generate 3 personas with goals, frictions, and quotes.',
    tools:['any'], deliverable:'3-persona document.',
    skillsBuilt:['persona-design','empathy'], tags:['cx','sales'] },
  { id:'CI-002', track:'customer-intelligence', title:'Sentiment Scanner', emoji:'❤️', difficulty:'intermediate', timeEstimate:30,
    description:'Feed customer reviews. AI categorizes sentiment and extracts themes.',
    detailedInstructions:'Use real (anonymized) reviews. Have AI score sentiment and cluster themes.',
    tools:['any'], deliverable:'Theme list + sentiment chart.',
    skillsBuilt:['nlp-output','clustering'], tags:['cx'] },
  { id:'CI-003', track:'customer-intelligence', title:'Journey Mapper', emoji:'🗺️', difficulty:'advanced', timeEstimate:40,
    description:'Map the full customer journey with pain points and opportunities.',
    detailedInstructions:'Define stages of your customer journey. Have AI generate pain points and opportunity ideas at each stage.',
    tools:['any'], deliverable:'A journey map document.',
    skillsBuilt:['journey-mapping','strategy'], tags:['cx'] },
  { id:'CI-004', track:'customer-intelligence', title:'Objection Handler', emoji:'🛡️', difficulty:'intermediate', timeEstimate:25,
    description:'List common objections. AI generates response frameworks for each.',
    detailedInstructions:'List 8 real objections. For each, get framework, suggested phrasing, and evidence to cite.',
    tools:['any'], deliverable:'Objection handling cheatsheet.',
    skillsBuilt:['sales-prep','framing'], tags:['sales'] },
  { id:'CI-005', track:'customer-intelligence', title:'Win/Loss Analyzer', emoji:'🏆', difficulty:'advanced', timeEstimate:35,
    description:'Feed deal notes. AI identifies patterns in wins vs losses.',
    detailedInstructions:'Paste anonymized win/loss notes. Have AI extract patterns and 5 recommendations.',
    tools:['any'], deliverable:'Pattern report + recommendations.',
    skillsBuilt:['pattern-recognition','analysis'], tags:['sales'] },

  // ─────────────── Research & Strategy (RS) ───────────────
  { id:'RS-001', track:'research-strategy', title:'Sparring Session', emoji:'🥊', difficulty:'intermediate', timeEstimate:30,
    description:'Pitch an idea to AI. Let it push back. Refine and write a one-pager.',
    detailedInstructions:'Pitch a real idea. Have AI play skeptical exec for 3 rounds. Write a refined one-pager.',
    tools:['claude','chatgpt'], deliverable:'The one-pager + transcript snippets.',
    skillsBuilt:['critique-resistance','refinement'], tags:['strategy'] },
  { id:'RS-002', track:'research-strategy', title:'Competitive Landscape', emoji:'🗺️', difficulty:'intermediate', timeEstimate:30,
    description:'Describe your market. AI maps competitors, differentiators, and gaps.',
    detailedInstructions:'Describe your market. Have AI produce a competitor grid with positioning and white-space.',
    tools:['any'], deliverable:'Competitor grid + 3 gap opportunities.',
    skillsBuilt:['competitive-analysis','positioning'], tags:['strategy'] },
  { id:'RS-003', track:'research-strategy', title:'SWOT Generator', emoji:'🧭', difficulty:'intermediate', timeEstimate:25,
    description:'Describe a product or initiative. AI builds a detailed SWOT analysis.',
    detailedInstructions:'Pick a real initiative. Have AI produce SWOT with evidence and 3 actions.',
    tools:['any'], deliverable:'The SWOT + action list.',
    skillsBuilt:['strategic-analysis','synthesis'], tags:['strategy'] },
  { id:'RS-004', track:'research-strategy', title:'Trend Spotter', emoji:'🔭', difficulty:'advanced', timeEstimate:35,
    description:'Give AI your industry. It identifies 5 emerging trends with evidence.',
    detailedInstructions:'Describe your industry. Have AI surface 5 trends with citations or examples, plus implications.',
    tools:['any'], deliverable:'5-trend brief.',
    skillsBuilt:['trend-analysis','foresight'], tags:['strategy','exec'] },
  { id:'RS-005', track:'research-strategy', title:'Business Case Builder', emoji:'📈', difficulty:'advanced', timeEstimate:45,
    description:'Describe a proposal. AI writes a full business case with ROI model.',
    detailedInstructions:'Describe a real proposal. Have AI produce summary, options, ROI math, risks, ask.',
    tools:['any'], deliverable:'Business case document.',
    skillsBuilt:['business-modeling','executive-comms'], tags:['exec','advanced'] },

  // ─────────────── Learning & Training Design (LD) ───────────────
  { id:'LD-001', track:'learning-design', title:'Build a Course', emoji:'🏫', difficulty:'advanced', timeEstimate:45,
    description:'Build a fully functional course in SCORM or HTML format.',
    detailedInstructions:'Pick a skill. Outline 5 modules. Have AI build interactive HTML modules with checkpoints.',
    tools:['claude','lovable'], deliverable:'Working course URL.',
    skillsBuilt:['curriculum-design','build'], tags:['l&d','build'] },
  { id:'LD-002', track:'learning-design', title:'Quiz Generator', emoji:'📝', difficulty:'intermediate', timeEstimate:20,
    description:'Give AI a topic. It generates a 10-question quiz with explanations.',
    detailedInstructions:'Pick a topic. Generate 10 multi-format questions with answer keys and explanations.',
    tools:['any'], deliverable:'Final quiz doc.',
    skillsBuilt:['assessment-design','clarity'], tags:['l&d'] },
  { id:'LD-003', track:'learning-design', title:'Knowledge Base', emoji:'📚', difficulty:'advanced', timeEstimate:40,
    description:'Build a searchable FAQ/knowledge base for a team or product.',
    detailedInstructions:'Aggregate 20 questions. Build a searchable KB site.',
    tools:['claude','lovable','base44'], deliverable:'Working KB URL.',
    skillsBuilt:['info-architecture','build'], tags:['l&d','build'] },
  { id:'LD-004', track:'learning-design', title:'Scenario Builder', emoji:'🎬', difficulty:'intermediate', timeEstimate:30,
    description:'Create 5 realistic workplace scenarios for role-play training.',
    detailedInstructions:'Pick a skill. Generate 5 scenarios with characters, context, and ideal response notes.',
    tools:['any'], deliverable:'Scenario pack.',
    skillsBuilt:['scenario-design','training-content'], tags:['l&d'] },
  { id:'LD-005', track:'learning-design', title:'Rubric Designer', emoji:'📏', difficulty:'intermediate', timeEstimate:25,
    description:'Describe an assessment. AI creates a detailed grading rubric.',
    detailedInstructions:'Describe what you assess. Have AI build a 4-level rubric with criteria and descriptors.',
    tools:['any'], deliverable:'The rubric document.',
    skillsBuilt:['rubric-design','assessment'], tags:['l&d'] },

  // ─────────────── Code & Technical (CT) ───────────────
  { id:'CT-001', track:'code-technical', title:'Code Reviewer', emoji:'🧐', difficulty:'intermediate', timeEstimate:25,
    description:'Feed AI a code snippet. Get a review with suggestions.',
    detailedInstructions:'Paste a function. Ask AI for review across correctness, readability, performance, and tests needed.',
    tools:['claude','chatgpt'], deliverable:'Review + applied changes.',
    skillsBuilt:['code-review','critique-use'], tags:['eng'] },
  { id:'CT-002', track:'code-technical', title:'API Doc Generator', emoji:'📘', difficulty:'intermediate', timeEstimate:30,
    description:'Describe an API. AI writes the full documentation.',
    detailedInstructions:'Describe an API. Have AI generate endpoint reference, examples, and error reference.',
    tools:['any'], deliverable:'Markdown API doc.',
    skillsBuilt:['documentation','structuring'], tags:['eng'] },
  { id:'CT-003', track:'code-technical', title:'Test Writer', emoji:'🧪', difficulty:'advanced', timeEstimate:35,
    description:'Give AI a function. It writes unit tests with edge cases.',
    detailedInstructions:'Paste a function. Ask for tests including edge cases and failure modes.',
    tools:['claude','chatgpt'], deliverable:'Test file with passing/failing tests as expected.',
    skillsBuilt:['testing','edge-thinking'], tags:['eng'] },
  { id:'CT-004', track:'code-technical', title:'Regex Builder', emoji:'🔣', difficulty:'intermediate', timeEstimate:20,
    description:'Describe a pattern in English. AI writes and explains the regex.',
    detailedInstructions:'Describe 3 patterns. Get regex, explanation, and 5 test strings.',
    tools:['any'], deliverable:'3 regex with examples.',
    skillsBuilt:['translation','testing'], tags:['eng','immediate-roi'] },
  { id:'CT-005', track:'code-technical', title:'Refactor Together', emoji:'🔧', difficulty:'intermediate', timeEstimate:30,
    description:'Take legacy code. Refactor with AI for clarity and tests.',
    detailedInstructions:'Take a real legacy snippet. Refactor with AI explaining each change.',
    tools:['claude','chatgpt'], deliverable:'Before/after + change log.',
    skillsBuilt:['refactoring','articulation'], tags:['eng'] },
  { id:'CT-006', track:'code-technical', title:'SQL from Plain English', emoji:'🗄️', difficulty:'beginner', timeEstimate:20,
    description:'Describe 3 queries in English. AI writes the SQL and explains.',
    detailedInstructions:'Pick 3 real queries you need. Get SQL + explanation + sample output shape.',
    tools:['any'], deliverable:'3 working SQL queries.',
    skillsBuilt:['sql','translation'], tags:['eng','immediate-roi'] },
  { id:'CT-007', track:'code-technical', title:'Bug Hunter', emoji:'🐛', difficulty:'intermediate', timeEstimate:25,
    description:'Paste a buggy snippet. Walk through the fix with AI as pair.',
    detailedInstructions:'Bring a real bug. Have AI hypothesize causes, suggest tests, then propose a fix.',
    tools:['claude','chatgpt'], deliverable:'Bug + fix + test that catches it.',
    skillsBuilt:['debugging','reasoning'], tags:['eng'] },

  // ─── Extra: Presentation ───
  { id:'PR-006', track:'presentation', title:'Stakeholder Map', emoji:'🧑‍🤝‍🧑', difficulty:'intermediate', timeEstimate:25,
    description:'For a project, generate a stakeholder map with influence × interest.',
    detailedInstructions:'List your stakeholders. Have AI rate influence/interest and suggest comms for each.',
    tools:['any'], deliverable:'Map + per-quadrant comms plan.',
    skillsBuilt:['stakeholder-mgmt','executive-thinking'], tags:['pm','exec'] },
  { id:'PR-007', track:'presentation', title:'Talking Points Generator', emoji:'🗣️', difficulty:'beginner', timeEstimate:15,
    description:'Generate 5 talking points for a 5-minute update.',
    detailedInstructions:'Pick a real update. Get 5 talking points + 1 anticipated question per point.',
    tools:['any'], deliverable:'Talking points doc.',
    skillsBuilt:['executive-comms','prep'], tags:['exec','immediate-roi'] },
  { id:'PR-008', track:'presentation', title:'Demo Script', emoji:'🎬', difficulty:'intermediate', timeEstimate:30,
    description:'Write a step-by-step demo script with screen cues for a product or process.',
    detailedInstructions:'Outline the demo flow. Have AI generate a script with screen cues and timing.',
    tools:['any'], deliverable:'Demo script.',
    skillsBuilt:['demo-craft','sequencing'], tags:['sales','pm'] },
  { id:'PR-009', track:'presentation', title:'Visual Metaphor Lab', emoji:'🎨', difficulty:'intermediate', timeEstimate:20,
    description:'Find 5 visual metaphors to make a tough concept simple.',
    detailedInstructions:'Pick a hard concept. Brainstorm 5 metaphors with AI, pick the best, sketch it.',
    tools:['any'], deliverable:'Top 3 metaphors + a chosen visual.',
    skillsBuilt:['simplification','communication'], tags:['comms'] },

  // ─── Extra: Creative & Storytelling ───
  { id:'CS-006', track:'creative-storytelling', title:'Workplace Mythology', emoji:'🗿', difficulty:'intermediate', timeEstimate:25,
    description:'Turn your team\'s rituals into a small mythology with characters and lore.',
    detailedInstructions:'Inventory rituals/quirks. Have AI write a short mythological telling.',
    tools:['any'], deliverable:'2-page mythology.',
    skillsBuilt:['team-storytelling','culture'], tags:['playful','team'] },
  { id:'CS-007', track:'creative-storytelling', title:'Future Headlines', emoji:'📰', difficulty:'beginner', timeEstimate:20,
    description:'Write 5 future-newspaper headlines about your team\'s success in 2030.',
    detailedInstructions:'Brainstorm 5 plausible headlines. Pick a favorite and write the supporting article.',
    tools:['any'], deliverable:'Headlines + 1 article.',
    skillsBuilt:['vision-setting','play'], tags:['warm-up','playful'] },
  { id:'CS-008', track:'creative-storytelling', title:'Mascot Maker', emoji:'🐉', difficulty:'beginner', timeEstimate:20,
    description:'Invent a mascot for your team. Include name, backstory, and visuals.',
    detailedInstructions:'Brainstorm traits. Generate the mascot image and a 100-word backstory.',
    tools:['chatgpt','gemini','copilot'], deliverable:'Image + backstory.',
    skillsBuilt:['brand-building','play'], tags:['playful','team'] },
  { id:'CS-009', track:'creative-storytelling', title:'Day-in-the-Life', emoji:'🌅', difficulty:'intermediate', timeEstimate:25,
    description:'Write a fictional day-in-the-life of your customer 3 years from now.',
    detailedInstructions:'Define your customer 3 years out. Write their full day from wake to sleep.',
    tools:['any'], deliverable:'1-page narrative.',
    skillsBuilt:['empathy','foresight'], tags:['cx','strategy'] },

  // ─── Extra: Customer Intelligence ───
  { id:'CI-006', track:'customer-intelligence', title:'NPS Narrative', emoji:'💬', difficulty:'intermediate', timeEstimate:25,
    description:'Turn raw NPS comments into a clear narrative with themes and quotes.',
    detailedInstructions:'Paste NPS comments. Extract top 3 themes, supporting quotes, and 3 actions.',
    tools:['any'], deliverable:'NPS narrative doc.',
    skillsBuilt:['qualitative-synthesis','cx'], tags:['cx','exec'] },
  { id:'CI-007', track:'customer-intelligence', title:'Churn Autopsy', emoji:'⚰️', difficulty:'advanced', timeEstimate:35,
    description:'Analyze churned customer notes. Identify root cause patterns.',
    detailedInstructions:'Compile churn notes. Have AI cluster root causes and propose 3 prevention plays.',
    tools:['any'], deliverable:'Churn pattern report.',
    skillsBuilt:['root-cause','prevention-planning'], tags:['cx','strategy'] },
  { id:'CI-008', track:'customer-intelligence', title:'Voice of Customer Digest', emoji:'📣', difficulty:'intermediate', timeEstimate:25,
    description:'Build a weekly VoC digest from support tickets and reviews.',
    detailedInstructions:'Use a week\'s tickets. Generate a top-themes digest with metrics and pulls.',
    tools:['any'], deliverable:'1-page VoC digest.',
    skillsBuilt:['recurring-reporting','synthesis'], tags:['cx'] },

  // ─── Extra: Research & Strategy ───
  { id:'RS-006', track:'research-strategy', title:'5-Year Vision Sketch', emoji:'🔮', difficulty:'advanced', timeEstimate:40,
    description:'Sketch a 5-year vision for your team or product.',
    detailedInstructions:'Describe today. Have AI propose 3 possible 5-year states with paths and risks.',
    tools:['any'], deliverable:'Vision document.',
    skillsBuilt:['vision','scenario-planning'], tags:['strategy','exec'] },
  { id:'RS-007', track:'research-strategy', title:'Hypothesis Tree', emoji:'🌲', difficulty:'intermediate', timeEstimate:30,
    description:'Decompose a strategic question into a tree of testable hypotheses.',
    detailedInstructions:'Pick a question. Have AI build a 3-level hypothesis tree with tests.',
    tools:['any'], deliverable:'Tree + 5 testable hypotheses.',
    skillsBuilt:['decomposition','strategy'], tags:['strategy','analytics'] },
  { id:'RS-008', track:'research-strategy', title:'Red Team Critique', emoji:'🟥', difficulty:'advanced', timeEstimate:30,
    description:'Have AI play harsh red-team on your plan. Strengthen with rebuttals.',
    detailedInstructions:'Paste your plan. Get top 10 attacks. Write rebuttals or revise plan.',
    tools:['claude','chatgpt'], deliverable:'Red-team transcript + revised plan.',
    skillsBuilt:['stress-testing','strategy'], tags:['strategy','exec'] },

  // ─── Extra: Learning & Training Design ───
  { id:'LD-006', track:'learning-design', title:'Microlearning Series', emoji:'🧱', difficulty:'intermediate', timeEstimate:30,
    description:'Build a 5-part microlearning series, each <3 minutes.',
    detailedInstructions:'Pick a topic. Outline 5 micro lessons with summary, example, quick check.',
    tools:['any'], deliverable:'5 micro lessons.',
    skillsBuilt:['micro-design','sequencing'], tags:['l&d'] },
  { id:'LD-007', track:'learning-design', title:'Role-Play Sims', emoji:'🎭', difficulty:'intermediate', timeEstimate:30,
    description:'Build 3 role-play simulations for a soft-skill topic.',
    detailedInstructions:'Pick a soft skill. Generate 3 scenarios with branching responses and scoring.',
    tools:['any'], deliverable:'3 scenarios with branches.',
    skillsBuilt:['simulation-design','training-content'], tags:['l&d'] },
  { id:'LD-008', track:'learning-design', title:'Pre/Post Assessment', emoji:'📐', difficulty:'intermediate', timeEstimate:25,
    description:'Design matched pre and post assessments to measure learning gain.',
    detailedInstructions:'Pick a topic. Build a 10-question pre and parallel 10-question post.',
    tools:['any'], deliverable:'Pre + post assessment.',
    skillsBuilt:['assessment-design','measurement'], tags:['l&d'] },

  // ─── Extra: Process Automation ───
  { id:'PA-007', track:'process-automation', title:'AI Co-Worker SOP', emoji:'🤝', difficulty:'intermediate', timeEstimate:30,
    description:'Write an SOP for using AI as a teammate on a recurring task.',
    detailedInstructions:'Pick a task you do weekly. Write the SOP including the prompts to use.',
    tools:['any'], deliverable:'SOP with embedded prompts.',
    skillsBuilt:['process-design','prompt-embedding'], tags:['ops','daily-use'] },
  { id:'PA-008', track:'process-automation', title:'Form Auto-Filler', emoji:'📝', difficulty:'intermediate', timeEstimate:25,
    description:'Build a tool that drafts responses to a recurring form.',
    detailedInstructions:'Pick a form you fill often. Build an AI-assisted drafter.',
    tools:['claude','lovable'], deliverable:'Working drafter URL.',
    skillsBuilt:['automation','templating'], tags:['ops','build'] },

  // ─── Extra: Visual ───
  { id:'VC-008', track:'visual-creation', title:'Icon Set', emoji:'🔣', difficulty:'intermediate', timeEstimate:25,
    description:'Generate a 10-icon set with consistent style for your product.',
    detailedInstructions:'List 10 concepts. Generate icons with a consistent style spec.',
    tools:['chatgpt','copilot'], deliverable:'10 icons in a sheet.',
    skillsBuilt:['style-consistency','icon-design'], tags:['design'] },
  { id:'VC-009', track:'visual-creation', title:'Slide Theme Builder', emoji:'🖼️', difficulty:'intermediate', timeEstimate:25,
    description:'Generate a slide theme: title slide, content slide, divider, closer.',
    detailedInstructions:'Brief your brand vibe. Generate 4 slide templates.',
    tools:['copilot','chatgpt'], deliverable:'4 slide templates.',
    skillsBuilt:['template-design','consistency'], tags:['design'] },

  // ─── Extra: Application Building ───
  { id:'AB-009', track:'application-building', title:'AI Helpdesk Mini', emoji:'🛟', difficulty:'advanced', timeEstimate:45,
    description:'Build a mini helpdesk that classifies and replies to messages.',
    detailedInstructions:'Define categories. Build an interface that classifies an input and drafts a reply.',
    tools:['claude','lovable'], deliverable:'Working helpdesk URL.',
    skillsBuilt:['classification-ui','build'], tags:['build','advanced'] },
  { id:'AB-010', track:'application-building', title:'1-Page Pitch Site', emoji:'📃', difficulty:'intermediate', timeEstimate:30,
    description:'Build a 1-page site pitching an internal idea.',
    detailedInstructions:'Draft your pitch. Build a single-page site with hero, benefits, CTA.',
    tools:['lovable','claude','base44'], deliverable:'Live URL.',
    skillsBuilt:['copy-and-build','marketing-page'], tags:['build'] },

  // ─── Extra: Prompt Engineering ───
  { id:'PE-011', track:'prompt-engineering', title:'Self-Critique Loop', emoji:'🔁', difficulty:'intermediate', timeEstimate:25,
    description:'Have AI critique its own output, then improve. Document the lift.',
    detailedInstructions:'Run a task. Have AI grade itself and rewrite. Compare versions.',
    tools:['any'], deliverable:'Original + critique + revised.',
    skillsBuilt:['self-critique','iteration'], tags:['practical'] },
  { id:'PE-012', track:'prompt-engineering', title:'Prompt Compression', emoji:'🗜️', difficulty:'intermediate', timeEstimate:20,
    description:'Take a long prompt. Compress it without losing fidelity.',
    detailedInstructions:'Pick a long prompt you use. Compress it 50%. Verify the output quality holds.',
    tools:['any'], deliverable:'Long + short + before/after outputs.',
    skillsBuilt:['compression','prompt-economics'], tags:['practical'] },

  // ─── Extra: Content Generation ───
  { id:'CG-011', track:'content-generation', title:'1:1 Prep Pack', emoji:'🪞', difficulty:'beginner', timeEstimate:20,
    description:'Turn quick notes into a polished 1:1 prep doc for a direct.',
    detailedInstructions:'List your raw notes for an upcoming 1:1. Get a structured prep doc back.',
    tools:['any'], deliverable:'A 1:1 prep doc.',
    skillsBuilt:['management','structure'], tags:['mgmt','daily-use'] },
  { id:'CG-012', track:'content-generation', title:'Apology Email', emoji:'🙇', difficulty:'beginner', timeEstimate:15,
    description:'Draft 3 versions of a hard apology email. Pick the most human one.',
    detailedInstructions:'Describe the situation. Get 3 versions across tones. Pick and polish.',
    tools:['any'], deliverable:'The 3 versions + your chosen send.',
    skillsBuilt:['tone','sensitive-comms'], tags:['practical'] }
];

if (typeof module !== 'undefined') module.exports = { ACTIVITIES };
